///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Mobile.AppSmiles.BuscaDeVoos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelecionarVoo recording.
    /// </summary>
    [TestModule("e4c2283a-9acb-4890-8d48-b8f00284129b", ModuleType.Recording, 1)]
    public partial class SelecionarVoo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static SelecionarVoo instance = new SelecionarVoo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelecionarVoo()
        {
            TipoPagamentoVooIda = "";
            TipoPagamentoVooVolta = "";
            TipoPagamentoTaxas = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelecionarVoo Instance
        {
            get { return instance; }
        }

#region Variables

        string _TipoPagamentoVooVolta;

        /// <summary>
        /// Gets or sets the value of variable TipoPagamentoVooVolta.
        /// </summary>
        [TestVariable("fe66cc98-a77f-4350-80fc-0b250f70e74d")]
        public string TipoPagamentoVooVolta
        {
            get { return _TipoPagamentoVooVolta; }
            set { _TipoPagamentoVooVolta = value; }
        }

        string _TipoPagamentoTaxas;

        /// <summary>
        /// Gets or sets the value of variable TipoPagamentoTaxas.
        /// </summary>
        [TestVariable("36df35ca-f674-425b-9419-5ca173ba4eba")]
        public string TipoPagamentoTaxas
        {
            get { return _TipoPagamentoTaxas; }
            set { _TipoPagamentoTaxas = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoPagamentoVooIda.
        /// </summary>
        [TestVariable("39c046fd-435a-434e-aa8d-5dc03bc3c1e6")]
        public string TipoPagamentoVooIda
        {
            get { return repo.TipoPagamentoVooIda; }
            set { repo.TipoPagamentoVooIda = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            SelecionarVoos(TipoPagamentoVooIda, TipoPagamentoVooVolta);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AppSmiles.Self, false, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'AppSmiles.TicketingActivity.ChekBoxAceitarTermos' at Center", repo.AppSmiles.TicketingActivity.ChekBoxAceitarTermosInfo, new RecordItemIndex(2));
            repo.AppSmiles.TicketingActivity.ChekBoxAceitarTermos.Touch();
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AppSmiles.Self, false, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'AppSmiles.TicketingActivity.BotaoContinuar2' at Center", repo.AppSmiles.TicketingActivity.BotaoContinuar2Info, new RecordItemIndex(4));
            repo.AppSmiles.TicketingActivity.BotaoContinuar2.Touch();
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AppSmiles.Self, false, new RecordItemIndex(5));
            
            SelecionarTaxas(TipoPagamentoTaxas);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AppSmiles.Self, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'AppSmiles.TicketingActivity.BotaoContinuar' at Center", repo.AppSmiles.TicketingActivity.BotaoContinuarInfo, new RecordItemIndex(8));
            repo.AppSmiles.TicketingActivity.BotaoContinuar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'AppSmiles.TicketingActivity.DadosDoAdulto1'.", repo.AppSmiles.TicketingActivity.DadosDoAdulto1Info, new RecordItemIndex(9));
            Validate.Exists(repo.AppSmiles.TicketingActivity.DadosDoAdulto1Info);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AppSmiles.Self, false, new RecordItemIndex(10));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
