///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Reserva_De_Voo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReservarVooSemCobrancaGateway recording.
    /// </summary>
    [TestModule("667df644-3726-4b2b-bfef-7d3f68c07ffc", ModuleType.Recording, 1)]
    public partial class ReservarVooSemCobrancaGateway : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static ReservarVooSemCobrancaGateway instance = new ReservarVooSemCobrancaGateway();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReservarVooSemCobrancaGateway()
        {
            TecladoVirtual = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReservarVooSemCobrancaGateway Instance
        {
            get { return instance; }
        }

#region Variables

        string _TecladoVirtual;

        /// <summary>
        /// Gets or sets the value of variable TecladoVirtual.
        /// </summary>
        [TestVariable("09891761-a31a-4af8-bd99-e30b476aaf87")]
        public string TecladoVirtual
        {
            get { return _TecladoVirtual; }
            set { _TecladoVirtual = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.Reserva_opcaoEmissao' at 7;8.", repo.SmilesOMelhorProgramaDeMilhasS1.Reserva_opcaoEmissaoInfo, new RecordItemIndex(0));
            repo.SmilesOMelhorProgramaDeMilhasS1.Reserva_opcaoEmissao.Click("7;8", 1);
            Delay.Milliseconds(490);
            
            WaitSmilesLoad();
            Delay.Milliseconds(0);
            
            InserirTecladoVirtual(TecladoVirtual);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_Processar' at 98;30.", repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_ProcessarInfo, new RecordItemIndex(3));
            repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_Processar.Click("98;30", 1);
            Delay.Milliseconds(490);
            
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(4));
            
            setReserva();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
