///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.ClubeSmiles
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ComprarSemTecladoVirtualClubeSmilesNew recording.
    /// </summary>
    [TestModule("fa5b6e66-c6c6-4bb6-8bb6-6def1b931765", ModuleType.Recording, 1)]
    public partial class ComprarSemTecladoVirtualClubeSmilesNew : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static ComprarSemTecladoVirtualClubeSmilesNew instance = new ComprarSemTecladoVirtualClubeSmilesNew();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ComprarSemTecladoVirtualClubeSmilesNew()
        {
            NomeTitular = "WELLINGTON SANTANA";
            NumeroCartao = "4111111111111111";
            MesVencimento = "6";
            AnoVencimento = "2016";
            CodigoSeguranca = "737";
            BandeiraCartaoCredito = "";
            DiaVencimentoClubeSmiles = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ComprarSemTecladoVirtualClubeSmilesNew Instance
        {
            get { return instance; }
        }

#region Variables

        string _NomeTitular;

        /// <summary>
        /// Gets or sets the value of variable NomeTitular.
        /// </summary>
        [TestVariable("e595b191-b11a-4776-b7cb-e672e2d0ce28")]
        public string NomeTitular
        {
            get { return _NomeTitular; }
            set { _NomeTitular = value; }
        }

        string _NumeroCartao;

        /// <summary>
        /// Gets or sets the value of variable NumeroCartao.
        /// </summary>
        [TestVariable("9409374a-1386-479d-b3be-fd0571dcd79f")]
        public string NumeroCartao
        {
            get { return _NumeroCartao; }
            set { _NumeroCartao = value; }
        }

        string _MesVencimento;

        /// <summary>
        /// Gets or sets the value of variable MesVencimento.
        /// </summary>
        [TestVariable("c74a95fe-593b-443c-b304-04c26f6f70af")]
        public string MesVencimento
        {
            get { return _MesVencimento; }
            set { _MesVencimento = value; }
        }

        string _AnoVencimento;

        /// <summary>
        /// Gets or sets the value of variable AnoVencimento.
        /// </summary>
        [TestVariable("74005bbc-fdef-4834-a74e-4757d3edb480")]
        public string AnoVencimento
        {
            get { return _AnoVencimento; }
            set { _AnoVencimento = value; }
        }

        string _CodigoSeguranca;

        /// <summary>
        /// Gets or sets the value of variable CodigoSeguranca.
        /// </summary>
        [TestVariable("0c44951f-8568-4446-9f6c-ea155c9a5f9f")]
        public string CodigoSeguranca
        {
            get { return _CodigoSeguranca; }
            set { _CodigoSeguranca = value; }
        }

        string _DiaVencimentoClubeSmiles;

        /// <summary>
        /// Gets or sets the value of variable DiaVencimentoClubeSmiles.
        /// </summary>
        [TestVariable("bb051692-ff6c-4490-badb-b080dfdb63b4")]
        public string DiaVencimentoClubeSmiles
        {
            get { return _DiaVencimentoClubeSmiles; }
            set { _DiaVencimentoClubeSmiles = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable BandeiraCartaoCredito.
        /// </summary>
        [TestVariable("bb897659-f7ce-4c21-bb34-48bc6cf90848")]
        public string BandeiraCartaoCredito
        {
            get { return repo.BandeiraCartaoCredito; }
            set { repo.BandeiraCartaoCredito = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //SeleclCreditCardFlag(BandeiraCartaoCredito);
            //Delay.Milliseconds(0);
            
            //WaitSmilesLoad();
            //Delay.Milliseconds(0);
            
            TypeKeys("//input[#'creditCardHolderName']", NomeTitular);
            Delay.Milliseconds(0);
            
            TypeKeys("//input[#'creditCardNumber']", NumeroCartao);
            Delay.Milliseconds(0);
            
            //SelectItemListBox("//select[#'expirationMonth']", MesVencimento);
            //Delay.Milliseconds(0);
            
            //SelectItemListBox("//select[#'expirationYear']", AnoVencimento);
            //Delay.Milliseconds(0);
            
            SelectItemListBoxAsHuman("//div[@Class~'cs-select cs-skin-silver payment'][1]", MesVencimento, "1");
            Delay.Milliseconds(0);
            
            SelectItemListBoxAsHuman("//div[@Class~'cs-select cs-skin-silver payment'][2]", AnoVencimento, "1");
            Delay.Milliseconds(0);
            
            TypeKeys("//input[#'secureCode']", CodigoSeguranca);
            Delay.Milliseconds(0);
            
            //SelecionarDiaVencimentoClubeSmiles(DiaVencimentoClubeSmiles);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.ClubeSmiles_LiEConcordoEmissao' at Center.", repo.SmilesOMelhorProgramaDeMilhasS1.ClubeSmiles_LiEConcordoEmissaoInfo, new RecordItemIndex(10));
            //repo.SmilesOMelhorProgramaDeMilhasS1.ClubeSmiles_LiEConcordoEmissao.Click(1);
            //Delay.Milliseconds(490);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.LiEConcordoComOsDoClubeSmilesE' at Center.", repo.SmilesOMelhorProgramaDeMilhasS1.LiEConcordoComOsDoClubeSmilesEInfo, new RecordItemIndex(11));
            repo.SmilesOMelhorProgramaDeMilhasS1.LiEConcordoComOsDoClubeSmilesE.Click(1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Next}'.", new RecordItemIndex(12));
            Keyboard.Press("{Next}", 1);
            Delay.Milliseconds(90);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_Processar' at UpperCenter.", repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_ProcessarInfo, new RecordItemIndex(13));
            repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_Processar.Click(Location.UpperCenter, 1);
            Delay.Milliseconds(490);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(14));
            Delay.Duration(1000, false);
            
            WaitLoad();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(16));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
