///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Busca_De_Voos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NBV_BuscarVoos recording.
    /// </summary>
    [TestModule("114e5d3c-fc7e-4a98-aaa8-98deb80778de", ModuleType.Recording, 1)]
    public partial class NBV_BuscarVoos : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static NBV_BuscarVoos instance = new NBV_BuscarVoos();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NBV_BuscarVoos()
        {
            De1 = "";
            Para1 = "";
            TipoTrajeto = "";
            De2 = "";
            Para2 = "";
            QuantidadeAdultos = "";
            QuantidadeBebes = "";
            QuantidadeCriancas = "";
            DataPartida1 = "";
            DataRetorno1 = "";
            DataPartida2 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NBV_BuscarVoos Instance
        {
            get { return instance; }
        }

#region Variables

        string _QuantidadeAdultos;

        /// <summary>
        /// Gets or sets the value of variable QuantidadeAdultos.
        /// </summary>
        [TestVariable("a58bf5cd-2f48-40de-9a96-9bd479239404")]
        public string QuantidadeAdultos
        {
            get { return _QuantidadeAdultos; }
            set { _QuantidadeAdultos = value; }
        }

        string _QuantidadeBebes;

        /// <summary>
        /// Gets or sets the value of variable QuantidadeBebes.
        /// </summary>
        [TestVariable("3b8e737f-d303-4bfb-b869-d864b08bd492")]
        public string QuantidadeBebes
        {
            get { return _QuantidadeBebes; }
            set { _QuantidadeBebes = value; }
        }

        string _QuantidadeCriancas;

        /// <summary>
        /// Gets or sets the value of variable QuantidadeCriancas.
        /// </summary>
        [TestVariable("fb343f8e-ecef-4052-ae18-542a1bb1b27a")]
        public string QuantidadeCriancas
        {
            get { return _QuantidadeCriancas; }
            set { _QuantidadeCriancas = value; }
        }

        string _DataPartida1;

        /// <summary>
        /// Gets or sets the value of variable DataPartida1.
        /// </summary>
        [TestVariable("e3500584-9e2c-4d85-af0e-c7374a0f8dc4")]
        public string DataPartida1
        {
            get { return _DataPartida1; }
            set { _DataPartida1 = value; }
        }

        string _DataRetorno1;

        /// <summary>
        /// Gets or sets the value of variable DataRetorno1.
        /// </summary>
        [TestVariable("59fc08b5-fb8f-48c1-b872-988159bf37bc")]
        public string DataRetorno1
        {
            get { return _DataRetorno1; }
            set { _DataRetorno1 = value; }
        }

        string _DataPartida2;

        /// <summary>
        /// Gets or sets the value of variable DataPartida2.
        /// </summary>
        [TestVariable("bd795038-dd28-4e94-b415-2ba8727ce8dd")]
        public string DataPartida2
        {
            get { return _DataPartida2; }
            set { _DataPartida2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable De1.
        /// </summary>
        [TestVariable("21c4dd2b-bf79-4146-b2a9-32da222961ee")]
        public string De1
        {
            get { return repo.De1; }
            set { repo.De1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Para1.
        /// </summary>
        [TestVariable("f20cdb57-0df9-4d4e-9496-d1e26cda6c52")]
        public string Para1
        {
            get { return repo.Para1; }
            set { repo.Para1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoTrajeto.
        /// </summary>
        [TestVariable("52855676-c818-4878-88fc-aa96aac7ba7c")]
        public string TipoTrajeto
        {
            get { return repo.TipoTrajeto; }
            set { repo.TipoTrajeto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable De2.
        /// </summary>
        [TestVariable("9c00a6ea-9b8a-426d-938a-348719024cce")]
        public string De2
        {
            get { return repo.De2; }
            set { repo.De2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Para2.
        /// </summary>
        [TestVariable("c1b59ef5-2398-4c68-83dc-bd29227ee871")]
        public string Para2
        {
            get { return repo.Para2; }
            set { repo.Para2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.MenuPrincipal_BuscarVoo' at LowerCenter.", repo.SmilesOMelhorProgramaDeMilhasS1.MenuPrincipal_BuscarVooInfo, new RecordItemIndex(0));
            repo.SmilesOMelhorProgramaDeMilhasS1.MenuPrincipal_BuscarVoo.Click(Location.LowerCenter, 1);
            Delay.Milliseconds(90);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            WaitSystemLoad("45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SmilesOMelhorProgramaDeMilhasS1.Validacao_EncontreSeuVoo2'.", repo.SmilesOMelhorProgramaDeMilhasS1.Validacao_EncontreSeuVoo2Info, new RecordItemIndex(3));
            Validate.Exists(repo.SmilesOMelhorProgramaDeMilhasS1.Validacao_EncontreSeuVoo2Info);
            Delay.Milliseconds(100);
            
            SelectItemFloatBox("//input[#'inputOrigin']", "//div[#'searchFlightTab']", De1);
            Delay.Milliseconds(100);
            
            SelectItemFloatBox("//input[#'inputDestination']", "//div[#'searchFlightTabBack']", Para1);
            Delay.Milliseconds(100);
            
            selectTrecho(TipoTrajeto);
            Delay.Milliseconds(0);
            
            SelectItemFloatBox("//input[#'inputOriginMs2']", "//div[#'searchFlightTabMs']", De2);
            Delay.Milliseconds(100);
            
            SelectItemFloatBox("//input[#'inputDestinationMs2']", "//div[#'searchFlightTabBackMs']", Para2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.BuscarVoo_De1' at Center.", repo.SmilesOMelhorProgramaDeMilhasS1.BuscarVoo_De1Info, new RecordItemIndex(9));
            repo.SmilesOMelhorProgramaDeMilhasS1.BuscarVoo_De1.Click(1);
            Delay.Milliseconds(490);
            
            SetCalendarDate("//input[@class~'date-picker-search' and @visible='True'][1]", DataPartida1);
            Delay.Milliseconds(0);
            
            SetCalendarDate("//input[@class~'date-picker-search' and @visible='True'][2]", DataRetorno1);
            Delay.Milliseconds(0);
            
            SetCalendarDate("//input[@class~'date-picker-search' and @visible='True'][2]", DataPartida2);
            Delay.Milliseconds(0);
            
            insertPassengers(QuantidadeAdultos, QuantidadeCriancas, QuantidadeBebes);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.BuscarVoo_BotaoBuscarVoo' at Center.", repo.SmilesOMelhorProgramaDeMilhasS1.BuscarVoo_BotaoBuscarVooInfo, new RecordItemIndex(14));
            repo.SmilesOMelhorProgramaDeMilhasS1.BuscarVoo_BotaoBuscarVoo.Click(1);
            Delay.Milliseconds(90);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            ClickIfExist();
            Delay.Milliseconds(0);
            
            WaitSystemLoad("60");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(18));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
