///////////////////////////////////////////////////////////////////////////////
//
// FormProgesso file was automatically generated by RANOREX.
// Your custom recording code should go in FormProgesso file.
// The designer will only add methods to FormProgesso file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.Busca_De_Voos
{
    public partial class Tooltip
    {
        /// <summary>
        /// FormProgesso method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SelectFlyPayment(string type)
        {
        	try {
        		if (type.Equals("") || type.Equals("NA") || type.Equals("N/A"))
        		{
        			return;
        		}
        		Report.Info("Selecting payment type '" + type + "'");
        		Smiles_UserCode.SelectFlyPaymentNew(repo,"",type,"");
        		Report.Info("Payment selected");
        	} catch (Exception) {
        		Report.Error("Tooltip - Error selecting payment type '" + type + "'");
        		throw new System.Exception("Tooltip.SelectFlyPayment");
        	}
        }

    }
}