///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Comprar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ComprarComTecladoVirtualETaxas recording.
    /// </summary>
    [TestModule("90de854c-65f3-4343-8a2f-0a75f97cfbd2", ModuleType.Recording, 1)]
    public partial class ComprarComTecladoVirtualETaxas : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static ComprarComTecladoVirtualETaxas instance = new ComprarComTecladoVirtualETaxas();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ComprarComTecladoVirtualETaxas()
        {
            BandeiraCartaoCredito = "";
            NomeTitular = "WELLINGTON SANTANA";
            NumeroCartao = "4111111111111111";
            MesVencimento = "6";
            CodigoSeguranca = "737";
            AnoVencimento = "2016";
            TecladoVirtual = "";
            TipoPagamentoTaxas = "";
            CPFSmilesID = "";
            IdentificacaoVoo = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ComprarComTecladoVirtualETaxas Instance
        {
            get { return instance; }
        }

#region Variables

        string _NomeTitular;

        /// <summary>
        /// Gets or sets the value of variable NomeTitular.
        /// </summary>
        [TestVariable("14683d85-a3f0-4624-b825-3f994902e580")]
        public string NomeTitular
        {
            get { return _NomeTitular; }
            set { _NomeTitular = value; }
        }

        string _NumeroCartao;

        /// <summary>
        /// Gets or sets the value of variable NumeroCartao.
        /// </summary>
        [TestVariable("5be48470-aa6f-4fee-ac20-5dee18fbf585")]
        public string NumeroCartao
        {
            get { return _NumeroCartao; }
            set { _NumeroCartao = value; }
        }

        string _MesVencimento;

        /// <summary>
        /// Gets or sets the value of variable MesVencimento.
        /// </summary>
        [TestVariable("22582732-3385-48f3-a2e4-59090f5dd3ae")]
        public string MesVencimento
        {
            get { return _MesVencimento; }
            set { _MesVencimento = value; }
        }

        string _CodigoSeguranca;

        /// <summary>
        /// Gets or sets the value of variable CodigoSeguranca.
        /// </summary>
        [TestVariable("9441087b-2a1d-47d4-9544-2b8bf0c144f5")]
        public string CodigoSeguranca
        {
            get { return _CodigoSeguranca; }
            set { _CodigoSeguranca = value; }
        }

        string _AnoVencimento;

        /// <summary>
        /// Gets or sets the value of variable AnoVencimento.
        /// </summary>
        [TestVariable("c00bfc2d-7dba-4ae2-a712-e2904cf329f6")]
        public string AnoVencimento
        {
            get { return _AnoVencimento; }
            set { _AnoVencimento = value; }
        }

        string _TecladoVirtual;

        /// <summary>
        /// Gets or sets the value of variable TecladoVirtual.
        /// </summary>
        [TestVariable("c5eee83d-e22d-4e5d-8eda-f8e7aafc3baf")]
        public string TecladoVirtual
        {
            get { return _TecladoVirtual; }
            set { _TecladoVirtual = value; }
        }

        string _TipoPagamentoTaxas;

        /// <summary>
        /// Gets or sets the value of variable TipoPagamentoTaxas.
        /// </summary>
        [TestVariable("9a6b4400-6318-43d5-99b3-b1238405a8ee")]
        public string TipoPagamentoTaxas
        {
            get { return _TipoPagamentoTaxas; }
            set { _TipoPagamentoTaxas = value; }
        }

        string _CPFSmilesID;

        /// <summary>
        /// Gets or sets the value of variable CPFSmilesID.
        /// </summary>
        [TestVariable("5fff8358-b9ae-48c3-bf38-4c4ef1898696")]
        public string CPFSmilesID
        {
            get { return _CPFSmilesID; }
            set { _CPFSmilesID = value; }
        }

        string _IdentificacaoVoo;

        /// <summary>
        /// Gets or sets the value of variable IdentificacaoVoo.
        /// </summary>
        [TestVariable("f50c2100-e0c5-46a0-a46a-dd3f69c6d1a5")]
        public string IdentificacaoVoo
        {
            get { return _IdentificacaoVoo; }
            set { _IdentificacaoVoo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable BandeiraCartaoCredito.
        /// </summary>
        [TestVariable("0e1e35fa-4359-4ec7-8497-3e6f92ae55f2")]
        public string BandeiraCartaoCredito
        {
            get { return repo.BandeiraCartaoCredito; }
            set { repo.BandeiraCartaoCredito = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            SelectRatePayment(TipoPagamentoTaxas, CPFSmilesID, IdentificacaoVoo);
            Delay.Milliseconds(0);
            
            SeleclCreditCardFlag(BandeiraCartaoCredito);
            Delay.Milliseconds(0);
            
            WaitSmilesLoad();
            Delay.Milliseconds(0);
            
            TypeKeys("//input[#'creditCardHolderName']", NomeTitular);
            Delay.Milliseconds(0);
            
            TypeKeys("//input[#'creditCardNumber']", NumeroCartao);
            Delay.Milliseconds(0);
            
            SelectItemListBox("//select[#'expirationMonth']", MesVencimento);
            Delay.Milliseconds(0);
            
            TypeKeys("//input[#'secureCode']", CodigoSeguranca);
            Delay.Milliseconds(0);
            
            SelectItemListBox("//select[#'expirationYear']", AnoVencimento);
            Delay.Milliseconds(0);
            
            InserirTecladoVirtual(TecladoVirtual);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_Processar' at Center.", repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_ProcessarInfo, new RecordItemIndex(9));
            repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_Processar.Click(1);
            Delay.Milliseconds(490);
            
            WaitLoad();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
