///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Teste
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InserirMilhas recording.
    /// </summary>
    [TestModule("c91b89f1-19f6-4a31-9a19-bc3cbebcc530", ModuleType.Recording, 1)]
    public partial class InserirMilhas : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static InserirMilhas instance = new InserirMilhas();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InserirMilhas()
        {
            NumSmiles = "";
            Milhas = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InserirMilhas Instance
        {
            get { return instance; }
        }

#region Variables

        string _NumSmiles;

        /// <summary>
        /// Gets or sets the value of variable NumSmiles.
        /// </summary>
        [TestVariable("1d62efde-9d0a-4ffa-8dfb-36e466741979")]
        public string NumSmiles
        {
            get { return _NumSmiles; }
            set { _NumSmiles = value; }
        }

        string _Milhas;

        /// <summary>
        /// Gets or sets the value of variable Milhas.
        /// </summary>
        [TestVariable("eec6b543-d273-430c-9566-8a79a579098e")]
        public string Milhas
        {
            get { return _Milhas; }
            set { _Milhas = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+Alt+A' Press.", new RecordItemIndex(0));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Alt, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            InserirBody(NumSmiles, Milhas);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aaaa'.", new RecordItemIndex(2));
            Keyboard.Press("aaaa");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
