///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;
using POCSmiles.Base_Dados;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.Resultado_Esperado
{
    public partial class RP_FinalizacaoReserva
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void FocusModalMenssage()
        {
        	if (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.Mensagem_CaixaMensagemInfo.AbsolutePath.ToResolvedString(),1000)) {
        	    	Report.Screenshot(repo.SmilesOMelhorProgramaDeMilhasS1.Mensagem_CaixaMensagem);
        	}
        }

        public void ValidateResult(string numSmiles, string identificacaoVoo)
        {
        	try {
        		Report.Info("Validating data");
        		string _voo1 = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "VOO_1");
        		if (!_voo1.Equals("")) {
        			if(!Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.PValidacao_EmissaoSuaViagemInfo.AbsolutePath.ToResolvedString(),"InnerText",_voo1,1000)){
    					Report.Error("Error trying to find '" + _voo1 + "'");
    				}
        		}
        		string _voo2 = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "VOO_2");
        		if (!_voo2.Equals("")) {
        			if(!Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.PValidacao_EmissaoSuaViagemInfo.AbsolutePath.ToResolvedString(),"InnerText",_voo2,1000)){
    					Report.Error("Error trying to find '" + _voo2 + "'");
    				}
        		}
        		
				string _adults = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "QNT_PASSAGEIROS");
				string _tarifaPorAdultoDinheiro = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "TARIFAS_POR_ADULTO_DINHEIRO");
				string _tarifaPorAdultoMilhas = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "TARIFAS_POR_ADULTO_MILHAS");
				string _taxasDinheiro = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "TAXAS_DINHEIRO");
				string _taxasMilhas = UtilsDB.getDataValuePNR(numSmiles, identificacaoVoo, "TAXAS_MILHAS");
        		if (!_adults.Equals("")) {
        			int totalAdultos = int.Parse(_adults);
					string totalDinheiro = string.Format("{0:C}",(_tarifaPorAdultoDinheiro.Equals("")?0:double.Parse(_tarifaPorAdultoDinheiro) * totalAdultos) + (_taxasDinheiro.Equals("")?0:double.Parse(_taxasDinheiro.ToString().Replace(".",","))));
					string totalMilhas = string.Format("{0:N}",(_tarifaPorAdultoMilhas.Equals("")?0:double.Parse(_tarifaPorAdultoMilhas) * totalAdultos) + (_taxasMilhas.Equals("")?0:double.Parse(_taxasMilhas)));
					if(!Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.PValidacao_EmissaoDadosCompraInfo.AbsolutePath.ToResolvedString(),"InnerText",totalDinheiro.Replace("$","\\$"),1000)){
        				Report.Error("Error trying to find '" + totalDinheiro + "'");
        			}
        			if(!Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.PValidacao_EmissaoDadosCompraInfo.AbsolutePath.ToResolvedString(),"InnerText", totalMilhas.Replace(",00",""),1000)){
						Report.Error("Error trying to find '" + totalMilhas.Replace(",00","") + "'");
        			}
        		}
        		Report.Info("Data validated");
        	} catch (Exception e) {
        		Report.Error("RP_ValidacaoEmissao - Error capturing validating emissao. Error:"  + e.Message);
        		throw new System.Exception("RP_ValidacaoEmissao.ValidateResult");
        	}
        } 
        private void updateDataBase(string numSmiles, string identificaoVoo){
        	try {
        		UtilsDB.updatePnrVooReservado(numSmiles, identificaoVoo, false);
        	} catch (Exception e) {
        		Report.Error("RP_ValidacaoEmissao - Error trying to update PNR. Error:"  + e.Message);
        		throw new System.Exception("RP_ValidacaoEmissao.updateDataBase");
        	}
        }
    }
}