///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.Resultado_Esperado
{
    public partial class RP_InserirPassageiros
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
		private void FocusModalMenssage()
        {
			if (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.Mensagem_CaixaMensagemInfo.AbsolutePath.ToResolvedString(),1000)) {
        	    	Report.Screenshot(repo.SmilesOMelhorProgramaDeMilhasS1.Mensagem_CaixaMensagem);
        	}
        }

        public void CaptureFlyDetails()
        {
        	try {
        		Report.Info("Capturing fly details");
        		if (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.DetalhesVoo_ExpandirInfo.AbsolutePath.ToResolvedString(),3000)) {
        			if (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][1]//tr[2]",3000)) {
        				int i = 2;
        				while (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][1]//tr[" + i +"]",3000)) {
        					WebElement e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][1]//tr[" + i +"]/td[2]/i";	
        					InitSetup.detalhesVooIda += 	e.Element.GetAttributeValueText("InnerText");
        					e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][1]//tr[" + i +"]/td[2]/b";
        					InitSetup.detalhesVooIda += "(" + e.Element.GetAttributeValueText("InnerText") + ") > ";
        					
        					e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][1]//tr[" + i +"]/td[4]/i";
        					InitSetup.detalhesVooIda += 	e.Element.GetAttributeValueText("InnerText");
        					e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][1]//tr[" + i +"]/td[4]/b";
        					InitSetup.detalhesVooIda += "(" + e.Element.GetAttributeValueText("InnerText") + ") | ";
        					i++;
        				}
        			}
        			if (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][2]//tr[2]",3000)) {
        				int i = 2;
        				while (Utils.CheckExist(repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][2]//tr[" + i +"]",3000)) {
        					WebElement e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][2]//tr[" + i +"]/td[2]/i";	
        					InitSetup.detalhesVooVolta += 	e.Element.GetAttributeValueText("InnerText");
        					e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][2]//tr[" + i +"]/td[2]/b";
        					InitSetup.detalhesVooVolta += "(" + e.Element.GetAttributeValueText("InnerText") + ") > ";
        					
        					e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][2]//tr[" + i +"]/td[4]/i";
        					InitSetup.detalhesVooVolta += 	e.Element.GetAttributeValueText("InnerText");
        					e = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//div[@class='bgWhite'][2]//tr[" + i +"]/td[4]/b";
        					InitSetup.detalhesVooVolta += "(" + e.Element.GetAttributeValueText("InnerText") + ") | ";
        					i++;
        				}
        			}
        		}
        		Report.Info("Fly details captured");
        	} catch (Exception) {
        		Report.Error("Erro trying to capture fly details");
        	}
        }
    }
}