///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.Resultado_Esperado
{
    public partial class SalvarDadosCadastro
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
		
        public static int initLinha = 1;
        public void SaveUserData(string excelPath)
        {
            try {
            	POCSmiles.ExcelRanorex.ExcelWriteCountA(excelPath,"Z2","A:A","Cadastro");
            	if (!System.IO.File.Exists(excelPath)) {
            		Report.Log(ReportLevel.Info, "Creating", "Creating the file: " + excelPath);
					POCSmiles.ExcelRanorex.ExcelCreateWorkbook(excelPath);
					POCSmiles.ExcelRanorex.ExcelCreateSheet(excelPath,"Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"A1","CPF","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"B1","NumSmiles","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"C1","Email","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"D1","Senha","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"E1","ClubeSmiles","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"F1","Data","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"Z1","NumLinha","Cadastro");
					POCSmiles.ExcelRanorex.ExcelWriteCountA(excelPath,"Z2","A:A","Cadastro");
            	}
            	
            	Report.Log(ReportLevel.Info, "Saving", "Saving the user: " + excelPath);
            	
            	initLinha = int.Parse(POCSmiles.ExcelRanorex.ExcelReadSingleCell(excelPath,"Z2","Cadastro")) + 1;
            	
            	POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"A" + initLinha,Cadastro.CadastrarUsuario.randomCPF,"Cadastro");
            	POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"B" + initLinha,captureNumSmiles(),"Cadastro");
            	POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"C" + initLinha,Cadastro.CadastrarUsuario.randomEmail,"Cadastro");
            	POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"D" + initLinha,Cadastro.CadastrarUsuario.Instance.Senha.ToString(),"Cadastro");
            	POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"E" + initLinha,"N","Cadastro");
            	POCSmiles.ExcelRanorex.ExcelWriteSingleCell(excelPath,"F" + initLinha,System.DateTime.Now.ToString(),"Cadastro");
            	POCSmiles.ExcelRanorex.ExcelWriteCountA(excelPath,"Z2","A:A","Cadastro");
            	
            	
            } catch (Exception e) {
            	Report.Error("Error saving the data in: " + excelPath);
                Console.WriteLine(e.ToString());
                Report.Screenshot();            	
            }
        }

        private string captureNumSmiles()
        {
            try {
            	Report.Log(ReportLevel.Info, "Capture", "Capture Smiles' number");
				SpanTag text = repo.SmilesOMelhorProgramaDeMilhasS1.AbsoluteBasePath.ToResolvedString() + "//span[@innertext~'^Seu número?.*$']";
            	return text.InnerText.Replace("Seu número Smiles é ","").Trim();
            } catch (Exception e) {
				Report.Error("Error capturing Smiles' number");
                Console.WriteLine(e.ToString());
                Report.Screenshot();            	
            }
            return "";
        }

        public void SaveUserDB(string URL)
        {
        	try {
        		Base_Dados.UtilsDB.insertUser(Cadastro.CadastrarUsuario.randomCPF,Cadastro.CadastrarUsuario.Instance.Senha.ToString(),URL);
        	}catch (Exception e) {
        		Report.Error("Database query execution  exception- Error inserting new user in data base: " + e.Message);	
        	}
        }

    }
}