///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Mobile.RxBrowser.DadosPassageiros
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InserirPassageiros recording.
    /// </summary>
    [TestModule("483fe99c-d542-481a-89c9-c88ded31416d", ModuleType.Recording, 1)]
    public partial class InserirPassageiros : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static InserirPassageiros instance = new InserirPassageiros();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InserirPassageiros()
        {
            PassageiroFavorito1 = "";
            Nome1 = "";
            Sobrenome1 = "";
            Genero1 = "";
            DataNascimento1 = "";
            Email1 = "";
            SalvarPassageiro1 = "";
            NumeroPassaporte1 = "";
            DataVencimentoPassaporte1 = "";
            PaisEmissor1 = "";
            PassageiroFavorito2 = "";
            Nome2 = "";
            Sobrenome2 = "";
            Genero2 = "";
            DataNascimento2 = "";
            Email2 = "";
            SalvarPassageiro2 = "";
            NumeroPassaporte2 = "";
            DataVencimentoPassaporte2 = "";
            PaisEmissor2 = "";
            PassageiroFavorito3 = "";
            Nome3 = "";
            Sobrenome3 = "";
            Genero3 = "";
            DataNascimento3 = "";
            Email3 = "";
            SalvarPassageiro3 = "";
            NumeroPassaporte3 = "";
            DataVencimentoPassaporte3 = "";
            PaisEmissor3 = "";
            PassageiroFavorito4 = "";
            Nome4 = "";
            Sobrenome4 = "";
            Genero4 = "";
            DataNascimento4 = "";
            Email4 = "";
            SalvarPassageiro4 = "";
            NumeroPassaporte4 = "";
            DataVencimentoPassaporte4 = "";
            PaisEmissor4 = "";
            PassageiroFavorito5 = "";
            Nome5 = "";
            Sobrenome5 = "";
            Genero5 = "";
            DataNascimento5 = "";
            Email5 = "";
            SalvarPassageiro5 = "";
            NumeroPassaporte5 = "";
            DataVencimentoPassaporte5 = "";
            PaisEmissor5 = "";
            PassageiroFavorito6 = "";
            Nome6 = "";
            Sobrenome6 = "";
            Genero6 = "";
            DataNascimento6 = "";
            Email6 = "";
            SalvarPassageiro6 = "";
            NumeroPassaporte6 = "";
            DataVencimentoPassaporte6 = "";
            PaisEmissor6 = "";
            PassageiroFavorito7 = "";
            Nome7 = "";
            Sobrenome7 = "";
            Genero7 = "";
            DataNascimento7 = "";
            Email7 = "";
            SalvarPassageiro7 = "";
            NumeroPassaporte7 = "";
            DataVencimentoPassaporte7 = "";
            PaisEmissor7 = "";
            PassageiroFavorito8 = "";
            Nome8 = "";
            Sobrenome8 = "";
            Genero8 = "";
            DataNascimento8 = "";
            Email8 = "";
            SalvarPassageiro8 = "";
            NumeroPassaporte8 = "";
            DataVencimentoPassaporte8 = "";
            PaisEmissor8 = "";
            PassageiroFavorito9 = "";
            Nome9 = "";
            Sobrenome9 = "";
            Genero9 = "";
            DataNascimento9 = "";
            Email9 = "";
            SalvarPassageiro9 = "";
            NumeroPassaporte9 = "";
            DataVencimentoPassaporte9 = "";
            PaisEmissor9 = "";
            PassageiroFavorito10 = "";
            Nome10 = "";
            Sobrenome10 = "";
            Genero10 = "";
            DataNascimento10 = "";
            Email10 = "";
            SalvarPassageiro10 = "";
            NumeroPassaporte10 = "";
            DataVencimentoPassaporte10 = "";
            PaisEmissor10 = "";
            PassageiroFavorito11 = "";
            Nome11 = "";
            Sobrenome11 = "";
            Genero11 = "";
            DataNascimento11 = "";
            Email11 = "";
            SalvarPassageiro11 = "";
            NumeroPassaporte11 = "";
            DataVencimentoPassaporte11 = "";
            PaisEmissor11 = "";
            PassageiroFavorito12 = "";
            Nome12 = "";
            Sobrenome12 = "";
            Genero12 = "";
            DataNascimento12 = "";
            Email12 = "";
            SalvarPassageiro12 = "";
            NumeroPassaporte12 = "";
            DataVencimentoPassaporte12 = "";
            PaisEmissor12 = "";
            PassageiroFavorito13 = "";
            Nome13 = "";
            Sobrenome13 = "";
            Genero13 = "";
            DataNascimento13 = "";
            Email13 = "";
            SalvarPassageiro13 = "";
            NumeroPassaporte13 = "";
            DataVencimentoPassaporte13 = "";
            PaisEmissor13 = "";
            PassageiroFavorito14 = "";
            Nome14 = "";
            Sobrenome14 = "";
            Genero14 = "";
            DataNascimento14 = "";
            Email14 = "";
            SalvarPassageiro14 = "";
            NumeroPassaporte14 = "";
            DataVencimentoPassaporte14 = "";
            PaisEmissor14 = "";
            PassageiroFavorito15 = "";
            Nome15 = "";
            Sobrenome15 = "";
            Genero15 = "";
            DataNascimento15 = "";
            Email15 = "";
            SalvarPassageiro15 = "";
            NumeroPassaporte15 = "";
            DataVencimentoPassaporte15 = "";
            PaisEmissor15 = "";
            PassageiroFavorito16 = "";
            Nome16 = "";
            Sobrenome16 = "";
            Genero16 = "";
            DataNascimento16 = "";
            Email16 = "";
            SalvarPassageiro16 = "";
            NumeroPassaporte16 = "";
            DataVencimentoPassaporte16 = "";
            PaisEmissor16 = "";
            PassageiroFavorito17 = "";
            Nome17 = "";
            Sobrenome17 = "";
            Genero17 = "";
            DataNascimento17 = "";
            Email17 = "";
            SalvarPassageiro17 = "";
            NumeroPassaporte17 = "";
            DataVencimentoPassaporte17 = "";
            PaisEmissor17 = "";
            PassageiroFavorito18 = "";
            Nome18 = "";
            Sobrenome18 = "";
            Genero18 = "";
            DataNascimento18 = "";
            Email18 = "";
            SalvarPassageiro18 = "";
            NumeroPassaporte18 = "";
            DataVencimentoPassaporte18 = "";
            PaisEmissor18 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InserirPassageiros Instance
        {
            get { return instance; }
        }

#region Variables

        string _PassageiroFavorito1;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito1.
        /// </summary>
        [TestVariable("377163a8-ebdc-412a-ad33-b0c686c6aa8f")]
        public string PassageiroFavorito1
        {
            get { return _PassageiroFavorito1; }
            set { _PassageiroFavorito1 = value; }
        }

        string _Nome1;

        /// <summary>
        /// Gets or sets the value of variable Nome1.
        /// </summary>
        [TestVariable("e8bea691-7697-4c90-9982-df0410e93feb")]
        public string Nome1
        {
            get { return _Nome1; }
            set { _Nome1 = value; }
        }

        string _Sobrenome1;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome1.
        /// </summary>
        [TestVariable("653dfbaf-6b63-4602-bde8-3290908db886")]
        public string Sobrenome1
        {
            get { return _Sobrenome1; }
            set { _Sobrenome1 = value; }
        }

        string _Genero1;

        /// <summary>
        /// Gets or sets the value of variable Genero1.
        /// </summary>
        [TestVariable("39cc20a5-2ebb-433b-901f-5ed073febb71")]
        public string Genero1
        {
            get { return _Genero1; }
            set { _Genero1 = value; }
        }

        string _DataNascimento1;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento1.
        /// </summary>
        [TestVariable("8362b891-3cbb-4a6f-9446-54474bad5799")]
        public string DataNascimento1
        {
            get { return _DataNascimento1; }
            set { _DataNascimento1 = value; }
        }

        string _Email1;

        /// <summary>
        /// Gets or sets the value of variable Email1.
        /// </summary>
        [TestVariable("1c7eb6b6-c2da-48e4-a1e2-079f67048925")]
        public string Email1
        {
            get { return _Email1; }
            set { _Email1 = value; }
        }

        string _SalvarPassageiro1;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro1.
        /// </summary>
        [TestVariable("b7874101-685e-44a4-ba40-2a9ad967ea18")]
        public string SalvarPassageiro1
        {
            get { return _SalvarPassageiro1; }
            set { _SalvarPassageiro1 = value; }
        }

        string _NumeroPassaporte1;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte1.
        /// </summary>
        [TestVariable("6605b5a8-9482-4842-9d78-86e1ce7bb0a7")]
        public string NumeroPassaporte1
        {
            get { return _NumeroPassaporte1; }
            set { _NumeroPassaporte1 = value; }
        }

        string _DataVencimentoPassaporte1;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte1.
        /// </summary>
        [TestVariable("103d6448-1d4a-4aa8-9add-89fba82cb893")]
        public string DataVencimentoPassaporte1
        {
            get { return _DataVencimentoPassaporte1; }
            set { _DataVencimentoPassaporte1 = value; }
        }

        string _PaisEmissor1;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor1.
        /// </summary>
        [TestVariable("d910e67a-1f20-44cc-ad6e-5d520b8d7c05")]
        public string PaisEmissor1
        {
            get { return _PaisEmissor1; }
            set { _PaisEmissor1 = value; }
        }

        string _PassageiroFavorito2;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito2.
        /// </summary>
        [TestVariable("cb0f0839-fd40-4c98-aa1d-94f552963dca")]
        public string PassageiroFavorito2
        {
            get { return _PassageiroFavorito2; }
            set { _PassageiroFavorito2 = value; }
        }

        string _Nome2;

        /// <summary>
        /// Gets or sets the value of variable Nome2.
        /// </summary>
        [TestVariable("1c8a1788-6e9a-469b-a076-0a22a31c787d")]
        public string Nome2
        {
            get { return _Nome2; }
            set { _Nome2 = value; }
        }

        string _Sobrenome2;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome2.
        /// </summary>
        [TestVariable("07ba7079-c4ba-4d6d-a07e-5cf7eb393403")]
        public string Sobrenome2
        {
            get { return _Sobrenome2; }
            set { _Sobrenome2 = value; }
        }

        string _Genero2;

        /// <summary>
        /// Gets or sets the value of variable Genero2.
        /// </summary>
        [TestVariable("0f88aa77-bfa9-49c1-aa44-ef0c771f944c")]
        public string Genero2
        {
            get { return _Genero2; }
            set { _Genero2 = value; }
        }

        string _DataNascimento2;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento2.
        /// </summary>
        [TestVariable("0d48ae6c-0c0e-4742-a00c-54e4f9164261")]
        public string DataNascimento2
        {
            get { return _DataNascimento2; }
            set { _DataNascimento2 = value; }
        }

        string _Email2;

        /// <summary>
        /// Gets or sets the value of variable Email2.
        /// </summary>
        [TestVariable("dca252f7-3fa8-4484-81d2-4a726ecb715f")]
        public string Email2
        {
            get { return _Email2; }
            set { _Email2 = value; }
        }

        string _SalvarPassageiro2;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro2.
        /// </summary>
        [TestVariable("cfee74c8-5f61-4480-a5d5-2eed27def6f9")]
        public string SalvarPassageiro2
        {
            get { return _SalvarPassageiro2; }
            set { _SalvarPassageiro2 = value; }
        }

        string _NumeroPassaporte2;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte2.
        /// </summary>
        [TestVariable("9b287198-ab29-4887-8c49-74bc5b8b2c76")]
        public string NumeroPassaporte2
        {
            get { return _NumeroPassaporte2; }
            set { _NumeroPassaporte2 = value; }
        }

        string _DataVencimentoPassaporte2;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte2.
        /// </summary>
        [TestVariable("96c5986d-48d6-4df7-9d61-28a81af77cbf")]
        public string DataVencimentoPassaporte2
        {
            get { return _DataVencimentoPassaporte2; }
            set { _DataVencimentoPassaporte2 = value; }
        }

        string _PaisEmissor2;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor2.
        /// </summary>
        [TestVariable("1289947c-d7d7-4a5d-9c56-412a71874e10")]
        public string PaisEmissor2
        {
            get { return _PaisEmissor2; }
            set { _PaisEmissor2 = value; }
        }

        string _PassageiroFavorito3;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito3.
        /// </summary>
        [TestVariable("cc0ec86d-4929-4450-8f0b-3a85778fbea4")]
        public string PassageiroFavorito3
        {
            get { return _PassageiroFavorito3; }
            set { _PassageiroFavorito3 = value; }
        }

        string _Nome3;

        /// <summary>
        /// Gets or sets the value of variable Nome3.
        /// </summary>
        [TestVariable("ad6adc95-00e1-4ec7-8cd9-99d24754c847")]
        public string Nome3
        {
            get { return _Nome3; }
            set { _Nome3 = value; }
        }

        string _Sobrenome3;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome3.
        /// </summary>
        [TestVariable("7e1e0d71-ebd2-45e7-93b2-0e7dd09aeebd")]
        public string Sobrenome3
        {
            get { return _Sobrenome3; }
            set { _Sobrenome3 = value; }
        }

        string _Genero3;

        /// <summary>
        /// Gets or sets the value of variable Genero3.
        /// </summary>
        [TestVariable("968063ea-de0e-4e33-9c5c-589327ef29f0")]
        public string Genero3
        {
            get { return _Genero3; }
            set { _Genero3 = value; }
        }

        string _DataNascimento3;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento3.
        /// </summary>
        [TestVariable("f97f915e-1c50-4b35-af37-e3ecdc762d50")]
        public string DataNascimento3
        {
            get { return _DataNascimento3; }
            set { _DataNascimento3 = value; }
        }

        string _Email3;

        /// <summary>
        /// Gets or sets the value of variable Email3.
        /// </summary>
        [TestVariable("aa65a780-f04e-482c-a99b-82a17b593cc8")]
        public string Email3
        {
            get { return _Email3; }
            set { _Email3 = value; }
        }

        string _SalvarPassageiro3;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro3.
        /// </summary>
        [TestVariable("ae5b8df9-7933-402c-8143-184624b3672f")]
        public string SalvarPassageiro3
        {
            get { return _SalvarPassageiro3; }
            set { _SalvarPassageiro3 = value; }
        }

        string _NumeroPassaporte3;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte3.
        /// </summary>
        [TestVariable("3bb8696e-dcd8-4e19-ae11-146ce194d4f3")]
        public string NumeroPassaporte3
        {
            get { return _NumeroPassaporte3; }
            set { _NumeroPassaporte3 = value; }
        }

        string _DataVencimentoPassaporte3;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte3.
        /// </summary>
        [TestVariable("3c0be866-92ae-498a-92cb-49d75e0f2039")]
        public string DataVencimentoPassaporte3
        {
            get { return _DataVencimentoPassaporte3; }
            set { _DataVencimentoPassaporte3 = value; }
        }

        string _PaisEmissor3;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor3.
        /// </summary>
        [TestVariable("8be164f3-62c4-4519-b42b-1114fe80e76c")]
        public string PaisEmissor3
        {
            get { return _PaisEmissor3; }
            set { _PaisEmissor3 = value; }
        }

        string _PassageiroFavorito4;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito4.
        /// </summary>
        [TestVariable("82e87b82-4f5f-434b-96ad-f9125d45aabb")]
        public string PassageiroFavorito4
        {
            get { return _PassageiroFavorito4; }
            set { _PassageiroFavorito4 = value; }
        }

        string _Nome4;

        /// <summary>
        /// Gets or sets the value of variable Nome4.
        /// </summary>
        [TestVariable("6bc8d9f3-3304-4464-944e-6c2f30a47b4b")]
        public string Nome4
        {
            get { return _Nome4; }
            set { _Nome4 = value; }
        }

        string _Sobrenome4;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome4.
        /// </summary>
        [TestVariable("ae2dea46-be01-4f20-be0e-b18fffc36f97")]
        public string Sobrenome4
        {
            get { return _Sobrenome4; }
            set { _Sobrenome4 = value; }
        }

        string _Genero4;

        /// <summary>
        /// Gets or sets the value of variable Genero4.
        /// </summary>
        [TestVariable("d72e10ee-2a10-4274-86e7-f35946099d67")]
        public string Genero4
        {
            get { return _Genero4; }
            set { _Genero4 = value; }
        }

        string _DataNascimento4;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento4.
        /// </summary>
        [TestVariable("c31c6285-2553-48c5-b521-e8929c05850a")]
        public string DataNascimento4
        {
            get { return _DataNascimento4; }
            set { _DataNascimento4 = value; }
        }

        string _Email4;

        /// <summary>
        /// Gets or sets the value of variable Email4.
        /// </summary>
        [TestVariable("d462bfe5-fd2b-47d5-a68e-64361c242768")]
        public string Email4
        {
            get { return _Email4; }
            set { _Email4 = value; }
        }

        string _SalvarPassageiro4;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro4.
        /// </summary>
        [TestVariable("fcf26339-357b-4fd1-bcae-0580053ffc02")]
        public string SalvarPassageiro4
        {
            get { return _SalvarPassageiro4; }
            set { _SalvarPassageiro4 = value; }
        }

        string _NumeroPassaporte4;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte4.
        /// </summary>
        [TestVariable("81bc13da-e10b-4ece-bdba-a8391069f58f")]
        public string NumeroPassaporte4
        {
            get { return _NumeroPassaporte4; }
            set { _NumeroPassaporte4 = value; }
        }

        string _DataVencimentoPassaporte4;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte4.
        /// </summary>
        [TestVariable("1a72c122-0a3b-4699-9e3a-5f105ad4301d")]
        public string DataVencimentoPassaporte4
        {
            get { return _DataVencimentoPassaporte4; }
            set { _DataVencimentoPassaporte4 = value; }
        }

        string _PaisEmissor4;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor4.
        /// </summary>
        [TestVariable("fd144edd-c736-488e-995a-38f6dd5b34a5")]
        public string PaisEmissor4
        {
            get { return _PaisEmissor4; }
            set { _PaisEmissor4 = value; }
        }

        string _PassageiroFavorito5;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito5.
        /// </summary>
        [TestVariable("49011534-91c8-4c21-93b3-b27ba9889df8")]
        public string PassageiroFavorito5
        {
            get { return _PassageiroFavorito5; }
            set { _PassageiroFavorito5 = value; }
        }

        string _Nome5;

        /// <summary>
        /// Gets or sets the value of variable Nome5.
        /// </summary>
        [TestVariable("d09c482d-958e-408b-ae91-352b7fb32b32")]
        public string Nome5
        {
            get { return _Nome5; }
            set { _Nome5 = value; }
        }

        string _Sobrenome5;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome5.
        /// </summary>
        [TestVariable("ec8612ac-9a42-4a2b-922f-b4f89a490b78")]
        public string Sobrenome5
        {
            get { return _Sobrenome5; }
            set { _Sobrenome5 = value; }
        }

        string _Genero5;

        /// <summary>
        /// Gets or sets the value of variable Genero5.
        /// </summary>
        [TestVariable("dec17497-8aba-4b28-be76-aa6eac8e4757")]
        public string Genero5
        {
            get { return _Genero5; }
            set { _Genero5 = value; }
        }

        string _DataNascimento5;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento5.
        /// </summary>
        [TestVariable("6f9459e3-bc6c-41ea-88f5-2bcd397b6ccd")]
        public string DataNascimento5
        {
            get { return _DataNascimento5; }
            set { _DataNascimento5 = value; }
        }

        string _Email5;

        /// <summary>
        /// Gets or sets the value of variable Email5.
        /// </summary>
        [TestVariable("993b60c9-a547-4845-ae90-3a924fb61740")]
        public string Email5
        {
            get { return _Email5; }
            set { _Email5 = value; }
        }

        string _SalvarPassageiro5;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro5.
        /// </summary>
        [TestVariable("5048c3b9-1c58-4222-80c7-21bbb7a7a03a")]
        public string SalvarPassageiro5
        {
            get { return _SalvarPassageiro5; }
            set { _SalvarPassageiro5 = value; }
        }

        string _NumeroPassaporte5;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte5.
        /// </summary>
        [TestVariable("68404430-ef2b-433d-b75e-898039a8d0e1")]
        public string NumeroPassaporte5
        {
            get { return _NumeroPassaporte5; }
            set { _NumeroPassaporte5 = value; }
        }

        string _DataVencimentoPassaporte5;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte5.
        /// </summary>
        [TestVariable("37c3b418-704d-4611-b01a-3f4360185f4a")]
        public string DataVencimentoPassaporte5
        {
            get { return _DataVencimentoPassaporte5; }
            set { _DataVencimentoPassaporte5 = value; }
        }

        string _PaisEmissor5;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor5.
        /// </summary>
        [TestVariable("c07d6e2e-3062-49b8-b965-fa9df8ff90dd")]
        public string PaisEmissor5
        {
            get { return _PaisEmissor5; }
            set { _PaisEmissor5 = value; }
        }

        string _PassageiroFavorito6;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito6.
        /// </summary>
        [TestVariable("c0d1ccf8-9c6c-4098-a348-014dbed1cbd6")]
        public string PassageiroFavorito6
        {
            get { return _PassageiroFavorito6; }
            set { _PassageiroFavorito6 = value; }
        }

        string _Nome6;

        /// <summary>
        /// Gets or sets the value of variable Nome6.
        /// </summary>
        [TestVariable("6097a5e5-6ffd-4d44-b286-f06ed3d6acb2")]
        public string Nome6
        {
            get { return _Nome6; }
            set { _Nome6 = value; }
        }

        string _Sobrenome6;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome6.
        /// </summary>
        [TestVariable("4bbb33ec-ac48-4877-a349-a9430acf24f3")]
        public string Sobrenome6
        {
            get { return _Sobrenome6; }
            set { _Sobrenome6 = value; }
        }

        string _Genero6;

        /// <summary>
        /// Gets or sets the value of variable Genero6.
        /// </summary>
        [TestVariable("50095b45-27d0-4270-a2a5-0d385449bba8")]
        public string Genero6
        {
            get { return _Genero6; }
            set { _Genero6 = value; }
        }

        string _DataNascimento6;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento6.
        /// </summary>
        [TestVariable("d1b52a83-3fdb-455f-af59-fd80aafb1d3d")]
        public string DataNascimento6
        {
            get { return _DataNascimento6; }
            set { _DataNascimento6 = value; }
        }

        string _Email6;

        /// <summary>
        /// Gets or sets the value of variable Email6.
        /// </summary>
        [TestVariable("a57f6c88-ed3f-4f13-8f04-54b30ba26b83")]
        public string Email6
        {
            get { return _Email6; }
            set { _Email6 = value; }
        }

        string _SalvarPassageiro6;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro6.
        /// </summary>
        [TestVariable("f5c22f83-8922-4f39-986c-cf08d894d18b")]
        public string SalvarPassageiro6
        {
            get { return _SalvarPassageiro6; }
            set { _SalvarPassageiro6 = value; }
        }

        string _NumeroPassaporte6;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte6.
        /// </summary>
        [TestVariable("6554211f-9f54-43d0-aeba-fb52cbe31ae4")]
        public string NumeroPassaporte6
        {
            get { return _NumeroPassaporte6; }
            set { _NumeroPassaporte6 = value; }
        }

        string _DataVencimentoPassaporte6;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte6.
        /// </summary>
        [TestVariable("783a1074-e457-4cff-b73c-0e968cfd7275")]
        public string DataVencimentoPassaporte6
        {
            get { return _DataVencimentoPassaporte6; }
            set { _DataVencimentoPassaporte6 = value; }
        }

        string _PaisEmissor6;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor6.
        /// </summary>
        [TestVariable("adc2eda1-36cc-42d5-ac68-760fd5ba334c")]
        public string PaisEmissor6
        {
            get { return _PaisEmissor6; }
            set { _PaisEmissor6 = value; }
        }

        string _PassageiroFavorito7;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito7.
        /// </summary>
        [TestVariable("8b0c065a-171c-4894-bf97-50e309c761f8")]
        public string PassageiroFavorito7
        {
            get { return _PassageiroFavorito7; }
            set { _PassageiroFavorito7 = value; }
        }

        string _Nome7;

        /// <summary>
        /// Gets or sets the value of variable Nome7.
        /// </summary>
        [TestVariable("6b483d6e-22eb-4df0-8644-59f2ab82d377")]
        public string Nome7
        {
            get { return _Nome7; }
            set { _Nome7 = value; }
        }

        string _Sobrenome7;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome7.
        /// </summary>
        [TestVariable("9f0b0ded-90c7-489d-9803-a3c1557d8a70")]
        public string Sobrenome7
        {
            get { return _Sobrenome7; }
            set { _Sobrenome7 = value; }
        }

        string _Genero7;

        /// <summary>
        /// Gets or sets the value of variable Genero7.
        /// </summary>
        [TestVariable("b7f7c58f-1e94-461b-a2b3-52e5aebf991c")]
        public string Genero7
        {
            get { return _Genero7; }
            set { _Genero7 = value; }
        }

        string _DataNascimento7;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento7.
        /// </summary>
        [TestVariable("db594540-bf68-4136-a59a-950351ce4080")]
        public string DataNascimento7
        {
            get { return _DataNascimento7; }
            set { _DataNascimento7 = value; }
        }

        string _Email7;

        /// <summary>
        /// Gets or sets the value of variable Email7.
        /// </summary>
        [TestVariable("c09a99e8-b600-4180-9ddd-2bb26a9cb7cb")]
        public string Email7
        {
            get { return _Email7; }
            set { _Email7 = value; }
        }

        string _SalvarPassageiro7;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro7.
        /// </summary>
        [TestVariable("96c0917d-b9aa-4b35-8ca6-647548623acb")]
        public string SalvarPassageiro7
        {
            get { return _SalvarPassageiro7; }
            set { _SalvarPassageiro7 = value; }
        }

        string _NumeroPassaporte7;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte7.
        /// </summary>
        [TestVariable("8b7922f2-3e20-4a18-8ae5-48d48d256795")]
        public string NumeroPassaporte7
        {
            get { return _NumeroPassaporte7; }
            set { _NumeroPassaporte7 = value; }
        }

        string _DataVencimentoPassaporte7;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte7.
        /// </summary>
        [TestVariable("160a2a8a-a03c-4e9a-b360-96596555dd39")]
        public string DataVencimentoPassaporte7
        {
            get { return _DataVencimentoPassaporte7; }
            set { _DataVencimentoPassaporte7 = value; }
        }

        string _PaisEmissor7;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor7.
        /// </summary>
        [TestVariable("b2d9bb64-a637-4030-817d-c2b3f980f37a")]
        public string PaisEmissor7
        {
            get { return _PaisEmissor7; }
            set { _PaisEmissor7 = value; }
        }

        string _PassageiroFavorito8;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito8.
        /// </summary>
        [TestVariable("7f5dc4f1-1fdc-4061-ac1d-f06cfbe3891f")]
        public string PassageiroFavorito8
        {
            get { return _PassageiroFavorito8; }
            set { _PassageiroFavorito8 = value; }
        }

        string _Nome8;

        /// <summary>
        /// Gets or sets the value of variable Nome8.
        /// </summary>
        [TestVariable("409e5425-f75f-4988-ba5d-98379fa7fe77")]
        public string Nome8
        {
            get { return _Nome8; }
            set { _Nome8 = value; }
        }

        string _Sobrenome8;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome8.
        /// </summary>
        [TestVariable("72b19482-2b93-49b5-b3ef-2767d7307e53")]
        public string Sobrenome8
        {
            get { return _Sobrenome8; }
            set { _Sobrenome8 = value; }
        }

        string _Genero8;

        /// <summary>
        /// Gets or sets the value of variable Genero8.
        /// </summary>
        [TestVariable("fb1b35e7-001b-4ca3-bebb-93c7c4ecb490")]
        public string Genero8
        {
            get { return _Genero8; }
            set { _Genero8 = value; }
        }

        string _DataNascimento8;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento8.
        /// </summary>
        [TestVariable("ee263840-d108-4e96-9d4a-33508acf19d7")]
        public string DataNascimento8
        {
            get { return _DataNascimento8; }
            set { _DataNascimento8 = value; }
        }

        string _Email8;

        /// <summary>
        /// Gets or sets the value of variable Email8.
        /// </summary>
        [TestVariable("444b2e73-fa74-4a8a-a95a-81a95d429047")]
        public string Email8
        {
            get { return _Email8; }
            set { _Email8 = value; }
        }

        string _SalvarPassageiro8;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro8.
        /// </summary>
        [TestVariable("7b767f75-c1ec-4d06-b8dd-bea898726119")]
        public string SalvarPassageiro8
        {
            get { return _SalvarPassageiro8; }
            set { _SalvarPassageiro8 = value; }
        }

        string _NumeroPassaporte8;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte8.
        /// </summary>
        [TestVariable("4e2a5c07-a874-410c-b1b9-ac94ec588769")]
        public string NumeroPassaporte8
        {
            get { return _NumeroPassaporte8; }
            set { _NumeroPassaporte8 = value; }
        }

        string _DataVencimentoPassaporte8;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte8.
        /// </summary>
        [TestVariable("ea0c3584-f39f-4f30-ba95-10d4d6cb8d6b")]
        public string DataVencimentoPassaporte8
        {
            get { return _DataVencimentoPassaporte8; }
            set { _DataVencimentoPassaporte8 = value; }
        }

        string _PaisEmissor8;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor8.
        /// </summary>
        [TestVariable("a008b2ac-1d36-4d8a-b6e2-852209a56bb7")]
        public string PaisEmissor8
        {
            get { return _PaisEmissor8; }
            set { _PaisEmissor8 = value; }
        }

        string _PassageiroFavorito9;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito9.
        /// </summary>
        [TestVariable("66a0dc10-961f-4b89-adfd-32b44cd5ac7b")]
        public string PassageiroFavorito9
        {
            get { return _PassageiroFavorito9; }
            set { _PassageiroFavorito9 = value; }
        }

        string _Nome9;

        /// <summary>
        /// Gets or sets the value of variable Nome9.
        /// </summary>
        [TestVariable("6b9683a5-04cf-4309-ada5-01a4961546b2")]
        public string Nome9
        {
            get { return _Nome9; }
            set { _Nome9 = value; }
        }

        string _Sobrenome9;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome9.
        /// </summary>
        [TestVariable("d297818b-714b-45a5-bc90-4fd5ccdf2a80")]
        public string Sobrenome9
        {
            get { return _Sobrenome9; }
            set { _Sobrenome9 = value; }
        }

        string _Genero9;

        /// <summary>
        /// Gets or sets the value of variable Genero9.
        /// </summary>
        [TestVariable("33d9903c-993c-4566-803d-db3f9794de68")]
        public string Genero9
        {
            get { return _Genero9; }
            set { _Genero9 = value; }
        }

        string _DataNascimento9;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento9.
        /// </summary>
        [TestVariable("e9e33a9c-2f2c-43b0-9262-c17a41dec5c3")]
        public string DataNascimento9
        {
            get { return _DataNascimento9; }
            set { _DataNascimento9 = value; }
        }

        string _Email9;

        /// <summary>
        /// Gets or sets the value of variable Email9.
        /// </summary>
        [TestVariable("beb8afd0-70c6-4af4-9223-e832473711e6")]
        public string Email9
        {
            get { return _Email9; }
            set { _Email9 = value; }
        }

        string _SalvarPassageiro9;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro9.
        /// </summary>
        [TestVariable("67ef2e0b-75b4-4d0f-a3af-8115a8aa620e")]
        public string SalvarPassageiro9
        {
            get { return _SalvarPassageiro9; }
            set { _SalvarPassageiro9 = value; }
        }

        string _NumeroPassaporte9;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte9.
        /// </summary>
        [TestVariable("f9373db7-9c58-4deb-aac5-9f2b933ad148")]
        public string NumeroPassaporte9
        {
            get { return _NumeroPassaporte9; }
            set { _NumeroPassaporte9 = value; }
        }

        string _DataVencimentoPassaporte9;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte9.
        /// </summary>
        [TestVariable("14588659-2ffc-4f7f-813d-ec6312c5c31d")]
        public string DataVencimentoPassaporte9
        {
            get { return _DataVencimentoPassaporte9; }
            set { _DataVencimentoPassaporte9 = value; }
        }

        string _PaisEmissor9;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor9.
        /// </summary>
        [TestVariable("5b803a7f-5b68-497b-836e-7f7fb5bb1898")]
        public string PaisEmissor9
        {
            get { return _PaisEmissor9; }
            set { _PaisEmissor9 = value; }
        }

        string _PassageiroFavorito10;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito10.
        /// </summary>
        [TestVariable("24c37397-ce44-41c4-abf2-8bfc368cb036")]
        public string PassageiroFavorito10
        {
            get { return _PassageiroFavorito10; }
            set { _PassageiroFavorito10 = value; }
        }

        string _Nome10;

        /// <summary>
        /// Gets or sets the value of variable Nome10.
        /// </summary>
        [TestVariable("5ea3509f-634b-4a12-b67a-2528a22fb88d")]
        public string Nome10
        {
            get { return _Nome10; }
            set { _Nome10 = value; }
        }

        string _Sobrenome10;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome10.
        /// </summary>
        [TestVariable("565c162b-6adc-402d-9c18-47d2159615e1")]
        public string Sobrenome10
        {
            get { return _Sobrenome10; }
            set { _Sobrenome10 = value; }
        }

        string _Genero10;

        /// <summary>
        /// Gets or sets the value of variable Genero10.
        /// </summary>
        [TestVariable("f7a8db59-6290-45fd-8483-3ea8fbc8f1e2")]
        public string Genero10
        {
            get { return _Genero10; }
            set { _Genero10 = value; }
        }

        string _DataNascimento10;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento10.
        /// </summary>
        [TestVariable("494ded68-74ee-4da3-bf2a-7cdc9b8e38cf")]
        public string DataNascimento10
        {
            get { return _DataNascimento10; }
            set { _DataNascimento10 = value; }
        }

        string _Email10;

        /// <summary>
        /// Gets or sets the value of variable Email10.
        /// </summary>
        [TestVariable("a53fb75e-6c8e-4aaa-872c-14b74de7cecb")]
        public string Email10
        {
            get { return _Email10; }
            set { _Email10 = value; }
        }

        string _SalvarPassageiro10;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro10.
        /// </summary>
        [TestVariable("e528c435-8ec2-43ce-8be9-ddef6c18cba4")]
        public string SalvarPassageiro10
        {
            get { return _SalvarPassageiro10; }
            set { _SalvarPassageiro10 = value; }
        }

        string _NumeroPassaporte10;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte10.
        /// </summary>
        [TestVariable("5dc1dff0-4a25-4e0b-be77-a7a000a67714")]
        public string NumeroPassaporte10
        {
            get { return _NumeroPassaporte10; }
            set { _NumeroPassaporte10 = value; }
        }

        string _DataVencimentoPassaporte10;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte10.
        /// </summary>
        [TestVariable("d69db9b1-fcbf-4f0e-8006-404a72fdd99f")]
        public string DataVencimentoPassaporte10
        {
            get { return _DataVencimentoPassaporte10; }
            set { _DataVencimentoPassaporte10 = value; }
        }

        string _PaisEmissor10;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor10.
        /// </summary>
        [TestVariable("595b07f7-38d9-4656-b730-a19d930ce4c1")]
        public string PaisEmissor10
        {
            get { return _PaisEmissor10; }
            set { _PaisEmissor10 = value; }
        }

        string _PassageiroFavorito11;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito11.
        /// </summary>
        [TestVariable("10cebcb3-0c8a-439b-a662-de66324ff48c")]
        public string PassageiroFavorito11
        {
            get { return _PassageiroFavorito11; }
            set { _PassageiroFavorito11 = value; }
        }

        string _Nome11;

        /// <summary>
        /// Gets or sets the value of variable Nome11.
        /// </summary>
        [TestVariable("f0fd62bb-f55a-46b0-8a16-f87f61a45e71")]
        public string Nome11
        {
            get { return _Nome11; }
            set { _Nome11 = value; }
        }

        string _Sobrenome11;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome11.
        /// </summary>
        [TestVariable("a1265105-9fbf-4d9c-8d81-8208e71381be")]
        public string Sobrenome11
        {
            get { return _Sobrenome11; }
            set { _Sobrenome11 = value; }
        }

        string _Genero11;

        /// <summary>
        /// Gets or sets the value of variable Genero11.
        /// </summary>
        [TestVariable("5ab30d69-868c-40a6-a7dc-5093ecfe8a17")]
        public string Genero11
        {
            get { return _Genero11; }
            set { _Genero11 = value; }
        }

        string _DataNascimento11;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento11.
        /// </summary>
        [TestVariable("c56e9c06-a69c-405b-b147-01bd42423ac7")]
        public string DataNascimento11
        {
            get { return _DataNascimento11; }
            set { _DataNascimento11 = value; }
        }

        string _Email11;

        /// <summary>
        /// Gets or sets the value of variable Email11.
        /// </summary>
        [TestVariable("f9f75eda-999a-4ecf-8f4b-31548fc1565c")]
        public string Email11
        {
            get { return _Email11; }
            set { _Email11 = value; }
        }

        string _SalvarPassageiro11;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro11.
        /// </summary>
        [TestVariable("e82646f3-e9e6-4b5c-bc1a-1e4a0aa3d838")]
        public string SalvarPassageiro11
        {
            get { return _SalvarPassageiro11; }
            set { _SalvarPassageiro11 = value; }
        }

        string _NumeroPassaporte11;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte11.
        /// </summary>
        [TestVariable("a44883c8-e300-4585-a91b-bfd12a81e8c6")]
        public string NumeroPassaporte11
        {
            get { return _NumeroPassaporte11; }
            set { _NumeroPassaporte11 = value; }
        }

        string _DataVencimentoPassaporte11;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte11.
        /// </summary>
        [TestVariable("cbbbcca0-7d33-4eb2-992d-902a1ed04d56")]
        public string DataVencimentoPassaporte11
        {
            get { return _DataVencimentoPassaporte11; }
            set { _DataVencimentoPassaporte11 = value; }
        }

        string _PaisEmissor11;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor11.
        /// </summary>
        [TestVariable("cdd0e198-2ae8-4cd6-a4cf-455a31eddcc0")]
        public string PaisEmissor11
        {
            get { return _PaisEmissor11; }
            set { _PaisEmissor11 = value; }
        }

        string _PassageiroFavorito12;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito12.
        /// </summary>
        [TestVariable("b0b9bfd2-010f-4b0e-a757-0d674e67f50d")]
        public string PassageiroFavorito12
        {
            get { return _PassageiroFavorito12; }
            set { _PassageiroFavorito12 = value; }
        }

        string _Nome12;

        /// <summary>
        /// Gets or sets the value of variable Nome12.
        /// </summary>
        [TestVariable("4cc7b6eb-5771-4b5f-897f-8bb77d86e469")]
        public string Nome12
        {
            get { return _Nome12; }
            set { _Nome12 = value; }
        }

        string _Sobrenome12;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome12.
        /// </summary>
        [TestVariable("d3ee1aa3-fd12-4c2c-8f8e-be8d97c21307")]
        public string Sobrenome12
        {
            get { return _Sobrenome12; }
            set { _Sobrenome12 = value; }
        }

        string _Genero12;

        /// <summary>
        /// Gets or sets the value of variable Genero12.
        /// </summary>
        [TestVariable("7e4a2bc5-9518-464f-9828-451be068c3b9")]
        public string Genero12
        {
            get { return _Genero12; }
            set { _Genero12 = value; }
        }

        string _DataNascimento12;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento12.
        /// </summary>
        [TestVariable("df448911-ff1e-4902-a120-1df293324fc0")]
        public string DataNascimento12
        {
            get { return _DataNascimento12; }
            set { _DataNascimento12 = value; }
        }

        string _Email12;

        /// <summary>
        /// Gets or sets the value of variable Email12.
        /// </summary>
        [TestVariable("568a50d2-7f33-4418-8aea-841d649dd9df")]
        public string Email12
        {
            get { return _Email12; }
            set { _Email12 = value; }
        }

        string _SalvarPassageiro12;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro12.
        /// </summary>
        [TestVariable("f623fd9a-5370-4788-8078-dafb7a7b5680")]
        public string SalvarPassageiro12
        {
            get { return _SalvarPassageiro12; }
            set { _SalvarPassageiro12 = value; }
        }

        string _NumeroPassaporte12;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte12.
        /// </summary>
        [TestVariable("e242ce90-9bce-4ce8-91e5-0b72819d5879")]
        public string NumeroPassaporte12
        {
            get { return _NumeroPassaporte12; }
            set { _NumeroPassaporte12 = value; }
        }

        string _DataVencimentoPassaporte12;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte12.
        /// </summary>
        [TestVariable("2b5a932a-8b21-488d-94b3-0ef8ac6c135d")]
        public string DataVencimentoPassaporte12
        {
            get { return _DataVencimentoPassaporte12; }
            set { _DataVencimentoPassaporte12 = value; }
        }

        string _PaisEmissor12;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor12.
        /// </summary>
        [TestVariable("7acba5ef-09c8-4544-b7f8-defd0128aa0d")]
        public string PaisEmissor12
        {
            get { return _PaisEmissor12; }
            set { _PaisEmissor12 = value; }
        }

        string _PassageiroFavorito13;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito13.
        /// </summary>
        [TestVariable("e93858f5-560b-4a94-980e-e1f6d6f47c27")]
        public string PassageiroFavorito13
        {
            get { return _PassageiroFavorito13; }
            set { _PassageiroFavorito13 = value; }
        }

        string _Nome13;

        /// <summary>
        /// Gets or sets the value of variable Nome13.
        /// </summary>
        [TestVariable("a22e7973-3bc6-4c83-a2aa-6d0238295f8d")]
        public string Nome13
        {
            get { return _Nome13; }
            set { _Nome13 = value; }
        }

        string _Sobrenome13;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome13.
        /// </summary>
        [TestVariable("061cd212-af83-44dd-a36c-31926b0eb759")]
        public string Sobrenome13
        {
            get { return _Sobrenome13; }
            set { _Sobrenome13 = value; }
        }

        string _Genero13;

        /// <summary>
        /// Gets or sets the value of variable Genero13.
        /// </summary>
        [TestVariable("df87451e-0cf7-48b9-a699-653510f5fa48")]
        public string Genero13
        {
            get { return _Genero13; }
            set { _Genero13 = value; }
        }

        string _DataNascimento13;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento13.
        /// </summary>
        [TestVariable("0b07bc3a-c081-4231-8cef-3f4f42c8bfb3")]
        public string DataNascimento13
        {
            get { return _DataNascimento13; }
            set { _DataNascimento13 = value; }
        }

        string _Email13;

        /// <summary>
        /// Gets or sets the value of variable Email13.
        /// </summary>
        [TestVariable("bf824c42-88c3-44cd-a35e-68dfc494bc30")]
        public string Email13
        {
            get { return _Email13; }
            set { _Email13 = value; }
        }

        string _SalvarPassageiro13;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro13.
        /// </summary>
        [TestVariable("e01547cf-957b-445c-aa86-c0c0079d428e")]
        public string SalvarPassageiro13
        {
            get { return _SalvarPassageiro13; }
            set { _SalvarPassageiro13 = value; }
        }

        string _NumeroPassaporte13;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte13.
        /// </summary>
        [TestVariable("2da4da68-ea79-4538-b18d-cec378e47f32")]
        public string NumeroPassaporte13
        {
            get { return _NumeroPassaporte13; }
            set { _NumeroPassaporte13 = value; }
        }

        string _DataVencimentoPassaporte13;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte13.
        /// </summary>
        [TestVariable("6188a96b-5a6a-497f-8be5-bb68b750bebe")]
        public string DataVencimentoPassaporte13
        {
            get { return _DataVencimentoPassaporte13; }
            set { _DataVencimentoPassaporte13 = value; }
        }

        string _PaisEmissor13;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor13.
        /// </summary>
        [TestVariable("afba3a09-0c2f-4a6b-925d-c532403899a8")]
        public string PaisEmissor13
        {
            get { return _PaisEmissor13; }
            set { _PaisEmissor13 = value; }
        }

        string _PassageiroFavorito14;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito14.
        /// </summary>
        [TestVariable("9e0a7f7c-9da1-4498-b356-1d131e260d62")]
        public string PassageiroFavorito14
        {
            get { return _PassageiroFavorito14; }
            set { _PassageiroFavorito14 = value; }
        }

        string _Nome14;

        /// <summary>
        /// Gets or sets the value of variable Nome14.
        /// </summary>
        [TestVariable("526048da-c604-4e66-bed4-4ae2a74b8bf5")]
        public string Nome14
        {
            get { return _Nome14; }
            set { _Nome14 = value; }
        }

        string _Sobrenome14;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome14.
        /// </summary>
        [TestVariable("a232cd1b-9f09-436f-814a-f996780b56df")]
        public string Sobrenome14
        {
            get { return _Sobrenome14; }
            set { _Sobrenome14 = value; }
        }

        string _Genero14;

        /// <summary>
        /// Gets or sets the value of variable Genero14.
        /// </summary>
        [TestVariable("d574c791-a620-426f-a4af-05c26e4e654a")]
        public string Genero14
        {
            get { return _Genero14; }
            set { _Genero14 = value; }
        }

        string _DataNascimento14;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento14.
        /// </summary>
        [TestVariable("8a3c342a-5be6-4fb3-b555-97bdb61ad5a0")]
        public string DataNascimento14
        {
            get { return _DataNascimento14; }
            set { _DataNascimento14 = value; }
        }

        string _Email14;

        /// <summary>
        /// Gets or sets the value of variable Email14.
        /// </summary>
        [TestVariable("beb30042-9c6a-4387-967d-c9e1bc2f3929")]
        public string Email14
        {
            get { return _Email14; }
            set { _Email14 = value; }
        }

        string _SalvarPassageiro14;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro14.
        /// </summary>
        [TestVariable("b542e079-b80d-43c6-a629-329817acee64")]
        public string SalvarPassageiro14
        {
            get { return _SalvarPassageiro14; }
            set { _SalvarPassageiro14 = value; }
        }

        string _NumeroPassaporte14;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte14.
        /// </summary>
        [TestVariable("f75ed45f-fb63-4ba4-9f04-1bf485f0872d")]
        public string NumeroPassaporte14
        {
            get { return _NumeroPassaporte14; }
            set { _NumeroPassaporte14 = value; }
        }

        string _DataVencimentoPassaporte14;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte14.
        /// </summary>
        [TestVariable("e15871ad-eb58-4e77-b3a4-d96f5da9cdcc")]
        public string DataVencimentoPassaporte14
        {
            get { return _DataVencimentoPassaporte14; }
            set { _DataVencimentoPassaporte14 = value; }
        }

        string _PaisEmissor14;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor14.
        /// </summary>
        [TestVariable("e72f874f-c44d-44c2-8577-623d55ff7b1a")]
        public string PaisEmissor14
        {
            get { return _PaisEmissor14; }
            set { _PaisEmissor14 = value; }
        }

        string _PassageiroFavorito15;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito15.
        /// </summary>
        [TestVariable("bfcf179c-d8f9-486e-a457-86d9a5a16f4e")]
        public string PassageiroFavorito15
        {
            get { return _PassageiroFavorito15; }
            set { _PassageiroFavorito15 = value; }
        }

        string _Nome15;

        /// <summary>
        /// Gets or sets the value of variable Nome15.
        /// </summary>
        [TestVariable("b56f9e56-f566-4a4a-bb75-4f8de867914b")]
        public string Nome15
        {
            get { return _Nome15; }
            set { _Nome15 = value; }
        }

        string _Sobrenome15;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome15.
        /// </summary>
        [TestVariable("37ea8ed5-01ce-4f5f-87bc-0f1970f6a05a")]
        public string Sobrenome15
        {
            get { return _Sobrenome15; }
            set { _Sobrenome15 = value; }
        }

        string _Genero15;

        /// <summary>
        /// Gets or sets the value of variable Genero15.
        /// </summary>
        [TestVariable("d0d7c906-8bf3-4ca5-b3b1-f081dfaccf04")]
        public string Genero15
        {
            get { return _Genero15; }
            set { _Genero15 = value; }
        }

        string _DataNascimento15;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento15.
        /// </summary>
        [TestVariable("dcdaf1a7-690b-4e7b-b818-c4f85f52fe43")]
        public string DataNascimento15
        {
            get { return _DataNascimento15; }
            set { _DataNascimento15 = value; }
        }

        string _Email15;

        /// <summary>
        /// Gets or sets the value of variable Email15.
        /// </summary>
        [TestVariable("e4c8bec4-6d82-4e7a-a633-2e09406c1de2")]
        public string Email15
        {
            get { return _Email15; }
            set { _Email15 = value; }
        }

        string _SalvarPassageiro15;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro15.
        /// </summary>
        [TestVariable("b1cdda2a-be88-4396-a20a-7ac75a42b4ff")]
        public string SalvarPassageiro15
        {
            get { return _SalvarPassageiro15; }
            set { _SalvarPassageiro15 = value; }
        }

        string _NumeroPassaporte15;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte15.
        /// </summary>
        [TestVariable("f57dc435-d615-466e-8ac1-d2fac60af67c")]
        public string NumeroPassaporte15
        {
            get { return _NumeroPassaporte15; }
            set { _NumeroPassaporte15 = value; }
        }

        string _DataVencimentoPassaporte15;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte15.
        /// </summary>
        [TestVariable("00a913cf-9e9c-41d9-8d47-1b2292b1edc3")]
        public string DataVencimentoPassaporte15
        {
            get { return _DataVencimentoPassaporte15; }
            set { _DataVencimentoPassaporte15 = value; }
        }

        string _PaisEmissor15;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor15.
        /// </summary>
        [TestVariable("3921216f-d003-4336-b70b-705df5e5804b")]
        public string PaisEmissor15
        {
            get { return _PaisEmissor15; }
            set { _PaisEmissor15 = value; }
        }

        string _PassageiroFavorito16;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito16.
        /// </summary>
        [TestVariable("f1bb57b4-79de-4458-b938-0bb1406bb441")]
        public string PassageiroFavorito16
        {
            get { return _PassageiroFavorito16; }
            set { _PassageiroFavorito16 = value; }
        }

        string _Nome16;

        /// <summary>
        /// Gets or sets the value of variable Nome16.
        /// </summary>
        [TestVariable("ae614d3d-7b45-4649-b063-f5e14eab27f8")]
        public string Nome16
        {
            get { return _Nome16; }
            set { _Nome16 = value; }
        }

        string _Sobrenome16;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome16.
        /// </summary>
        [TestVariable("e1571602-b574-44f7-938b-2cc33993fdd0")]
        public string Sobrenome16
        {
            get { return _Sobrenome16; }
            set { _Sobrenome16 = value; }
        }

        string _Genero16;

        /// <summary>
        /// Gets or sets the value of variable Genero16.
        /// </summary>
        [TestVariable("17cacd4e-e31a-4d06-8de6-030307c8e9ff")]
        public string Genero16
        {
            get { return _Genero16; }
            set { _Genero16 = value; }
        }

        string _DataNascimento16;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento16.
        /// </summary>
        [TestVariable("32a4e22b-ed09-43bb-ac1b-7e24927bdd58")]
        public string DataNascimento16
        {
            get { return _DataNascimento16; }
            set { _DataNascimento16 = value; }
        }

        string _Email16;

        /// <summary>
        /// Gets or sets the value of variable Email16.
        /// </summary>
        [TestVariable("54b7ee98-ecc9-48bd-bbaf-a2c0bf453783")]
        public string Email16
        {
            get { return _Email16; }
            set { _Email16 = value; }
        }

        string _SalvarPassageiro16;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro16.
        /// </summary>
        [TestVariable("ac245330-c4a3-443b-83b7-4431627d6ae9")]
        public string SalvarPassageiro16
        {
            get { return _SalvarPassageiro16; }
            set { _SalvarPassageiro16 = value; }
        }

        string _NumeroPassaporte16;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte16.
        /// </summary>
        [TestVariable("29404249-892d-42d4-8ee0-ee6a659f51de")]
        public string NumeroPassaporte16
        {
            get { return _NumeroPassaporte16; }
            set { _NumeroPassaporte16 = value; }
        }

        string _DataVencimentoPassaporte16;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte16.
        /// </summary>
        [TestVariable("21abad91-2d41-493c-aa25-4b1a36f722ed")]
        public string DataVencimentoPassaporte16
        {
            get { return _DataVencimentoPassaporte16; }
            set { _DataVencimentoPassaporte16 = value; }
        }

        string _PaisEmissor16;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor16.
        /// </summary>
        [TestVariable("3f2328c5-d58f-4304-a9cd-c39db38d5731")]
        public string PaisEmissor16
        {
            get { return _PaisEmissor16; }
            set { _PaisEmissor16 = value; }
        }

        string _PassageiroFavorito17;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito17.
        /// </summary>
        [TestVariable("36a0b745-d34d-4591-928d-9670b121392e")]
        public string PassageiroFavorito17
        {
            get { return _PassageiroFavorito17; }
            set { _PassageiroFavorito17 = value; }
        }

        string _Nome17;

        /// <summary>
        /// Gets or sets the value of variable Nome17.
        /// </summary>
        [TestVariable("32468566-54a2-4300-b1b1-75e0c34b43fd")]
        public string Nome17
        {
            get { return _Nome17; }
            set { _Nome17 = value; }
        }

        string _Sobrenome17;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome17.
        /// </summary>
        [TestVariable("b163fb77-736c-45bc-a432-e49cd084da92")]
        public string Sobrenome17
        {
            get { return _Sobrenome17; }
            set { _Sobrenome17 = value; }
        }

        string _Genero17;

        /// <summary>
        /// Gets or sets the value of variable Genero17.
        /// </summary>
        [TestVariable("4afcf1a4-b8a7-435c-8cd0-3ff95e5c9b61")]
        public string Genero17
        {
            get { return _Genero17; }
            set { _Genero17 = value; }
        }

        string _DataNascimento17;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento17.
        /// </summary>
        [TestVariable("6d1d7919-e451-415b-876b-830b884a67fa")]
        public string DataNascimento17
        {
            get { return _DataNascimento17; }
            set { _DataNascimento17 = value; }
        }

        string _Email17;

        /// <summary>
        /// Gets or sets the value of variable Email17.
        /// </summary>
        [TestVariable("7eda93c7-a10a-48aa-801b-324f2bd1aeb9")]
        public string Email17
        {
            get { return _Email17; }
            set { _Email17 = value; }
        }

        string _SalvarPassageiro17;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro17.
        /// </summary>
        [TestVariable("20c4723c-85c5-4271-b897-13c6979f1a06")]
        public string SalvarPassageiro17
        {
            get { return _SalvarPassageiro17; }
            set { _SalvarPassageiro17 = value; }
        }

        string _NumeroPassaporte17;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte17.
        /// </summary>
        [TestVariable("5b08b714-b3f7-4475-aa1a-3d83422ace25")]
        public string NumeroPassaporte17
        {
            get { return _NumeroPassaporte17; }
            set { _NumeroPassaporte17 = value; }
        }

        string _DataVencimentoPassaporte17;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte17.
        /// </summary>
        [TestVariable("b9824a58-08fa-415e-8f96-83e804a1ca34")]
        public string DataVencimentoPassaporte17
        {
            get { return _DataVencimentoPassaporte17; }
            set { _DataVencimentoPassaporte17 = value; }
        }

        string _PaisEmissor17;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor17.
        /// </summary>
        [TestVariable("30a0002b-48f8-431a-bc03-a27a163b4c04")]
        public string PaisEmissor17
        {
            get { return _PaisEmissor17; }
            set { _PaisEmissor17 = value; }
        }

        string _PassageiroFavorito18;

        /// <summary>
        /// Gets or sets the value of variable PassageiroFavorito18.
        /// </summary>
        [TestVariable("5ab60c2f-5fc1-4f00-b52b-369e127b5447")]
        public string PassageiroFavorito18
        {
            get { return _PassageiroFavorito18; }
            set { _PassageiroFavorito18 = value; }
        }

        string _Nome18;

        /// <summary>
        /// Gets or sets the value of variable Nome18.
        /// </summary>
        [TestVariable("c27eebaa-990d-49d9-87da-b158c8f645ff")]
        public string Nome18
        {
            get { return _Nome18; }
            set { _Nome18 = value; }
        }

        string _Sobrenome18;

        /// <summary>
        /// Gets or sets the value of variable Sobrenome18.
        /// </summary>
        [TestVariable("4745faa0-2ba0-490a-a128-a57660aa14ca")]
        public string Sobrenome18
        {
            get { return _Sobrenome18; }
            set { _Sobrenome18 = value; }
        }

        string _Genero18;

        /// <summary>
        /// Gets or sets the value of variable Genero18.
        /// </summary>
        [TestVariable("83207c12-a8dc-4252-b12c-28f1a97c4fcd")]
        public string Genero18
        {
            get { return _Genero18; }
            set { _Genero18 = value; }
        }

        string _DataNascimento18;

        /// <summary>
        /// Gets or sets the value of variable DataNascimento18.
        /// </summary>
        [TestVariable("acdb102d-008e-4923-992e-d6bb525bc333")]
        public string DataNascimento18
        {
            get { return _DataNascimento18; }
            set { _DataNascimento18 = value; }
        }

        string _Email18;

        /// <summary>
        /// Gets or sets the value of variable Email18.
        /// </summary>
        [TestVariable("9ce2046d-9755-4e58-aa28-046a77457be8")]
        public string Email18
        {
            get { return _Email18; }
            set { _Email18 = value; }
        }

        string _SalvarPassageiro18;

        /// <summary>
        /// Gets or sets the value of variable SalvarPassageiro18.
        /// </summary>
        [TestVariable("b9a4604a-6e70-406c-bcb0-7cdd9d1c1138")]
        public string SalvarPassageiro18
        {
            get { return _SalvarPassageiro18; }
            set { _SalvarPassageiro18 = value; }
        }

        string _NumeroPassaporte18;

        /// <summary>
        /// Gets or sets the value of variable NumeroPassaporte18.
        /// </summary>
        [TestVariable("54540d4e-0ab8-4bc8-aadb-350929b6db81")]
        public string NumeroPassaporte18
        {
            get { return _NumeroPassaporte18; }
            set { _NumeroPassaporte18 = value; }
        }

        string _DataVencimentoPassaporte18;

        /// <summary>
        /// Gets or sets the value of variable DataVencimentoPassaporte18.
        /// </summary>
        [TestVariable("812c5ec5-c48f-4218-98cd-77dbc777b1ae")]
        public string DataVencimentoPassaporte18
        {
            get { return _DataVencimentoPassaporte18; }
            set { _DataVencimentoPassaporte18 = value; }
        }

        string _PaisEmissor18;

        /// <summary>
        /// Gets or sets the value of variable PaisEmissor18.
        /// </summary>
        [TestVariable("803f0479-ee2a-48f6-b88e-3d9bd59abec1")]
        public string PaisEmissor18
        {
            get { return _PaisEmissor18; }
            set { _PaisEmissor18 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Dispositivo.
        /// </summary>
        [TestVariable("da3e43bb-7e4d-42d3-af80-4010368868c5")]
        public string Dispositivo
        {
            get { return repo.Dispositivo; }
            set { repo.Dispositivo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            InsertPassengers("0", PassageiroFavorito1, Nome1, Sobrenome1, Genero1, DataNascimento1, Email1, SalvarPassageiro1, NumeroPassaporte1, DataVencimentoPassaporte1, PaisEmissor1);
            Delay.Milliseconds(0);
            
            InsertPassengers("1", PassageiroFavorito2, Nome2, Sobrenome2, Genero2, DataNascimento2, Email2, SalvarPassageiro2, NumeroPassaporte2, DataVencimentoPassaporte2, PaisEmissor2);
            Delay.Milliseconds(0);
            
            InsertPassengers("2", PassageiroFavorito3, Nome3, Sobrenome3, Genero3, DataNascimento3, Email3, SalvarPassageiro3, NumeroPassaporte3, DataVencimentoPassaporte3, PaisEmissor3);
            Delay.Milliseconds(0);
            
            InsertPassengers("3", PassageiroFavorito4, Nome4, Sobrenome4, Genero4, DataNascimento4, Email4, SalvarPassageiro4, NumeroPassaporte4, DataVencimentoPassaporte4, PaisEmissor4);
            Delay.Milliseconds(0);
            
            InsertPassengers("4", PassageiroFavorito5, Nome5, Sobrenome5, Genero5, DataNascimento5, Email5, SalvarPassageiro5, NumeroPassaporte5, DataVencimentoPassaporte5, PaisEmissor5);
            Delay.Milliseconds(0);
            
            InsertPassengers("5", PassageiroFavorito6, Nome6, Sobrenome6, Genero6, DataNascimento6, Email6, SalvarPassageiro6, NumeroPassaporte6, DataVencimentoPassaporte6, PaisEmissor6);
            Delay.Milliseconds(0);
            
            InsertPassengers("6", PassageiroFavorito7, Nome7, Sobrenome7, Genero7, DataNascimento7, Email7, SalvarPassageiro7, NumeroPassaporte7, DataVencimentoPassaporte7, PaisEmissor7);
            Delay.Milliseconds(0);
            
            InsertPassengers("7", PassageiroFavorito8, Nome8, Sobrenome8, Genero8, DataNascimento8, Email8, SalvarPassageiro8, NumeroPassaporte8, DataVencimentoPassaporte8, PaisEmissor8);
            Delay.Milliseconds(0);
            
            InsertPassengers("8", PassageiroFavorito9, Nome9, Sobrenome9, Genero9, DataNascimento9, Email9, SalvarPassageiro9, NumeroPassaporte9, DataVencimentoPassaporte9, PaisEmissor9);
            Delay.Milliseconds(0);
            
            InsertPassengers("9", PassageiroFavorito10, Nome10, Sobrenome10, Genero10, DataNascimento10, Email10, SalvarPassageiro10, NumeroPassaporte10, DataVencimentoPassaporte10, PaisEmissor10);
            Delay.Milliseconds(0);
            
            InsertPassengers("10", PassageiroFavorito11, Nome11, Sobrenome11, Genero11, DataNascimento11, Email11, SalvarPassageiro11, NumeroPassaporte11, DataVencimentoPassaporte11, PaisEmissor11);
            Delay.Milliseconds(0);
            
            InsertPassengers("11", PassageiroFavorito12, Nome12, Sobrenome12, Genero12, DataNascimento12, Email12, SalvarPassageiro12, NumeroPassaporte12, DataVencimentoPassaporte12, PaisEmissor12);
            Delay.Milliseconds(0);
            
            InsertPassengers("12", PassageiroFavorito13, Nome13, Sobrenome13, Genero13, DataNascimento13, Email13, SalvarPassageiro13, NumeroPassaporte13, DataVencimentoPassaporte13, PaisEmissor13);
            Delay.Milliseconds(0);
            
            InsertPassengers("13", PassageiroFavorito14, Nome14, Sobrenome14, Genero14, DataNascimento14, Email14, SalvarPassageiro14, NumeroPassaporte14, DataVencimentoPassaporte14, PaisEmissor14);
            Delay.Milliseconds(0);
            
            InsertPassengers("14", PassageiroFavorito15, Nome15, Sobrenome15, Genero15, DataNascimento15, Email15, SalvarPassageiro15, NumeroPassaporte15, DataVencimentoPassaporte15, PaisEmissor15);
            Delay.Milliseconds(0);
            
            InsertPassengers("15", PassageiroFavorito16, Nome16, Sobrenome16, Genero16, DataNascimento16, Email16, SalvarPassageiro16, NumeroPassaporte16, DataVencimentoPassaporte16, PaisEmissor16);
            Delay.Milliseconds(0);
            
            InsertPassengers("16", PassageiroFavorito17, Nome17, Sobrenome17, Genero17, DataNascimento17, Email17, SalvarPassageiro17, NumeroPassaporte17, DataVencimentoPassaporte17, PaisEmissor17);
            Delay.Milliseconds(0);
            
            InsertPassengers("17", PassageiroFavorito18, Nome18, Sobrenome18, Genero18, DataNascimento18, Email18, SalvarPassageiro18, NumeroPassaporte18, DataVencimentoPassaporte18, PaisEmissor18);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.RxBrowser.Self, false, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'RxBrowser.Dom.Button_Continuar' at Center", repo.RxBrowser.Dom.Button_ContinuarInfo, new RecordItemIndex(19));
            repo.RxBrowser.Dom.Button_Continuar.Touch();
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.RxBrowser.Self, false, new RecordItemIndex(20));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
