///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;
using POCSmiles.Reserva_De_Voo;
using POCSmiles.Resultado_Esperado;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles
{
	public partial class InitSetup
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
		
        public static string detalhesVooIda = "";
		public static string detalhesVooVolta = "";
		public static int ida1 = 0;
        public static int ida2 = 0;
        public static int volta1 = 0;
        public static int volta2 = 0;
        public static System.DateTime inicioExecucao;
        public static bool gravarTempo;
        
        public void InitData()
        {
        	gravarTempo = true;
        	inicioExecucao = System.DateTime.Now;
	       	SalvarDadosExcel.voo1 = "";
	        SalvarDadosExcel.voo2 = "";
	        SalvarDadosExcel.tAdultoDinheiro = "0,00";
	        SalvarDadosExcel.tAdultoMilhas = "0";
	        SalvarDadosExcel.taxasDinheiro = "0,00";
	        SalvarDadosExcel.taxasMilhas = "0";
	        SalvarDadosExcel.codigoConfimacao = "";
	        SalvarDadosExcel.vooReservado = "false";
	        
	        RP_ValidacaoEmissao._voo1 = "";
			RP_ValidacaoEmissao._voo2 = "";
			RP_ValidacaoEmissao._tarifaPorAdultoMilhas = "0";
			RP_ValidacaoEmissao._tarifaPorAdultoDinheiro = "0,00";
			RP_ValidacaoEmissao._taxasDinheiro = "0,00";
			RP_ValidacaoEmissao._taxasMilhas = "0";
			RP_ValidacaoEmissao._passenger1 = "";
			
			CapturarMilhasLogin.totalMilhas = "";
			
			CapturarReembolsoCancelamento.milhasEmissaoBilhete = "";
        	CapturarReembolsoCancelamento.milhasTaxaEmbarque = "";
        	CapturarReembolsoCancelamento.milhasMarcacaoAssento = "";
        	CapturarReembolsoCancelamento.milhasExpirarSuaConta = "";
        	CapturarReembolsoCancelamento.milhasReembolsadas = "";
        	Cadastro.CadastrarUsuario.randomCPF = "";
			Cadastro.CadastrarUsuario.randomEmail = "";
			
			SelecionarVooAssento.taxasDinheiro = "";
			SelecionarVooAssento.taxasMilhas = "";
			
			SalvarDadosCadastro.initLinha = 1;
			ida1 = 0;
			ida2 = 0;
			volta1 = 0;
			volta2 = 0;
			
			detalhesVooIda = "";
			detalhesVooVolta = "";
			
        }
        
    }
}