///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.Compra_De_Milhas
{
    public partial class ComprarMilhasNEW
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void TypeKeys(string milhas)
        {
        	try {
        		Report.Info("Typing keys: " + milhas);
        		repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_QntMilhas.PressKeys((int.Parse(milhas) / 1000).ToString());
        		Report.Info(milhas + " was typed");
        	} catch (Exception e) {
        		Report.Failure("Error typing milles on field. Error: " + e.Message);
        	}
        }

        public void SelectVoucher(string voucher)
        {
        	try {
        		if (voucher.Equals("") || voucher.Equals("N/A") || voucher.Equals("NA")) {
        			return;
        		}
        		Report.Log(ReportLevel.Info, "Select", "Selecting the item " + voucher);
        		repo.SmilesOMelhorProgramaDeMilhasS1.ComprarMilhas_LinkConferirVouchers.Click(Duration.FromMilliseconds(1));
        		repo.SmilesOMelhorProgramaDeMilhasS1.CompraMilhas_Voucher.Click(Duration.FromMilliseconds(1));
        		Report.Log(ReportLevel.Info,"Item '" + voucher + "' selected");
        	} catch (Exception) {
        		Report.Error("ComprarMilhas - Error launched trying to insert voucher '" + voucher + "'");
        		throw new System.Exception("ComprarMilhas.SelectVoucher");
        	}
        }

        public void WaitSmilesLoad()
        {
        	try {
        		Report.Info("Waiting Smiles' loading GIF");
        		Smiles_UserCode.WaitSmilesLoadGIF(repo,60);
        		Report.Info("Smiles' loading GIF desapeared");
        	} catch (Exception) {
        		Report.Error("SelecionarVoo - Error waiting Smiles' loading GIF desapear");
        		throw new System.Exception("SelecionarVoo.WaitSmilesLoad");
        	}
        }

    }
}