///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;
using POCSmiles.Reserva_De_Voo;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.Resultado_Esperado
{
    public partial class RP_SelecionarAssentos
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SaveDataDB(string identifiacacaoVoo, string numSMiles, string url)
        {
        	try {
        		if (identifiacacaoVoo.Equals("")) {
        			identifiacacaoVoo = POCSmiles.Resultado_Esperado.SalvarDadosExcel.codigoConfimacao;
        		}
        		Base_Dados.UtilsDB.updateChairSelected(identifiacacaoVoo,numSMiles,url,SelecionarVooAssento.taxasMilhas, SelecionarVooAssento.taxasDinheiro.Replace("R$","").Trim());
        	}catch (Exception e) {
        		Report.Error("Database query execution  exception- Error updating user in data base: " + e.Message);	
        	}
        }

    }
}