///////////////////////////////////////////////////////////////////////////////
//
// FormProgesso file was automatically generated by RANOREX.
// Your custom recording code should go in FormProgesso file.
// The designer will only add methods to FormProgesso file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.AtendimentoOnline
{
    public partial class RP_AtendimentoEmilia
    {
        /// <summary>
        /// FormProgesso method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CloseApplicationEmilia()
        {
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'Emilia'.", repo.Emilia.SelfInfo);
            if (Utils.CheckExist(repo.Emilia.AbsoluteBasePath.ToResolvedString(), 2000))
            {
            	Keyboard.Press(System.Windows.Forms.Keys.F4 | System.Windows.Forms.Keys.Alt, 62, Keyboard.DefaultKeyPressTime, 1, true);
            	Keyboard.Press("{ESCAPE}");
            }
        }

    }
}