///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POCSmiles.AtendimentoOnline
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Emilia element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("e9cf99ba-57ca-4958-aa91-b5118b846492")]
    public partial class Emilia : RepoGenBaseFolder
    {
        static Emilia instance = new Emilia();
        EmiliaFolders.RxBrowserAppFolder _rxbrowser;
        EmiliaFolders.SmilesOMelhorProgramaDeMilhasS1AppFolder _smilesomelhorprogramademilhass1;

        /// <summary>
        /// Gets the singleton class instance representing the Emilia element repository.
        /// </summary>
        [RepositoryFolder("e9cf99ba-57ca-4958-aa91-b5118b846492")]
        public static Emilia Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Emilia() 
            : base("Emilia", "/", null, 0, false, "e9cf99ba-57ca-4958-aa91-b5118b846492", ".\\RepositoryImages\\Emiliae9cf99ba.rximgres")
        {
            _rxbrowser = new EmiliaFolders.RxBrowserAppFolder(this);
            _smilesomelhorprogramademilhass1 = new EmiliaFolders.SmilesOMelhorProgramaDeMilhasS1AppFolder(this);
        }

#region Variables

        string _URL = "";

        /// <summary>
        /// Gets or sets the value of variable URL.
        /// </summary>
        [TestVariable("ee0efb26-0aef-4036-b5f6-c912bb3637d9")]
        public string URL
        {
            get { return _URL; }
            set { _URL = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e9cf99ba-57ca-4958-aa91-b5118b846492")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxBrowser folder.
        /// </summary>
        [RepositoryFolder("aebb0893-29d3-4fa6-bc4c-cbeaaf10bf38")]
        public virtual EmiliaFolders.RxBrowserAppFolder RxBrowser
        {
            get { return _rxbrowser; }
        }

        /// <summary>
        /// The SmilesOMelhorProgramaDeMilhasS1 folder.
        /// </summary>
        [RepositoryFolder("9bb164db-b0c4-4d27-bbb8-ffab30fc4aaf")]
        public virtual EmiliaFolders.SmilesOMelhorProgramaDeMilhasS1AppFolder SmilesOMelhorProgramaDeMilhasS1
        {
            get { return _smilesomelhorprogramademilhass1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class EmiliaFolders
    {
        /// <summary>
        /// The RxBrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("aebb0893-29d3-4fa6-bc4c-cbeaaf10bf38")]
        public partial class RxBrowserAppFolder : RepoGenBaseFolder
        {
            EmiliaFolders.DomAppFolder _dom;
            RepoItemInfo _uidatepickerInfo;

            /// <summary>
            /// Creates a new RxBrowser  folder.
            /// </summary>
            public RxBrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxBrowser", "/mobileapp[@title='ranorex.RxBrowser']", parentFolder, 10000, null, false, "aebb0893-29d3-4fa6-bc4c-cbeaaf10bf38", "")
            {
                _dom = new EmiliaFolders.DomAppFolder(this);
                _uidatepickerInfo = new RepoItemInfo(this, "UIDatePicker", "datetime[@platformclass='UIDatePicker']", 30000, null, "bf317859-b149-471f-87b5-2e994d2cfd7e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aebb0893-29d3-4fa6-bc4c-cbeaaf10bf38")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aebb0893-29d3-4fa6-bc4c-cbeaaf10bf38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UIDatePicker item.
            /// </summary>
            [RepositoryItem("bf317859-b149-471f-87b5-2e994d2cfd7e")]
            public virtual Ranorex.DateTime UIDatePicker
            {
                get
                {
                    return _uidatepickerInfo.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The UIDatePicker item info.
            /// </summary>
            [RepositoryItemInfo("bf317859-b149-471f-87b5-2e994d2cfd7e")]
            public virtual RepoItemInfo UIDatePickerInfo
            {
                get
                {
                    return _uidatepickerInfo;
                }
            }

            /// <summary>
            /// The Dom folder.
            /// </summary>
            [RepositoryFolder("896b282b-52c3-44de-a91c-6d52560ab526")]
            public virtual EmiliaFolders.DomAppFolder Dom
            {
                get { return _dom; }
            }
        }

        /// <summary>
        /// The DomAppFolder folder.
        /// </summary>
        [RepositoryFolder("896b282b-52c3-44de-a91c-6d52560ab526")]
        public partial class DomAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _home_menuprincipalInfo;
            RepoItemInfo _menuprincipal_buscarvooInfo;
            RepoItemInfo _buscarvoo_origemInfo;
            RepoItemInfo _buscarvoo_origem2Info;
            RepoItemInfo _buscarvoo_destinoInfo;
            RepoItemInfo _buscarvoo_destino2Info;
            RepoItemInfo _checkbox_somenteidaInfo;
            RepoItemInfo _calendar_data1Info;
            RepoItemInfo _calendar_data2Info;
            RepoItemInfo _button_buscarvooInfo;
            RepoItemInfo _button_adicionartrechoInfo;
            RepoItemInfo _button_addadultoInfo;
            RepoItemInfo _button_addcriancaInfo;
            RepoItemInfo _button_addbebeInfo;
            RepoItemInfo _button_entrarInfo;
            RepoItemInfo _input_usuarioInfo;
            RepoItemInfo _input_senhaInfo;
            RepoItemInfo _button_submeterloginInfo;
            RepoItemInfo _span_saldomilhasloginInfo;
            RepoItemInfo _home_entrarInfo;
            RepoItemInfo _a_sairInfo;
            RepoItemInfo _button_refazerbuscaInfo;
            RepoItemInfo _input_taxasdinheroInfo;
            RepoItemInfo _input_taxasmilhasInfo;

            /// <summary>
            /// Creates a new Dom  folder.
            /// </summary>
            public DomAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dom", ".//dom", parentFolder, 10000, null, false, "896b282b-52c3-44de-a91c-6d52560ab526", "")
            {
                _home_menuprincipalInfo = new RepoItemInfo(this, "Home_MenuPrincipal", ".//div[#'showMenu']", 30000, null, "94e5852e-d1cd-4827-b49e-e22bc21b98eb");
                _menuprincipal_buscarvooInfo = new RepoItemInfo(this, "MenuPrincipal_BuscarVoo", ".//span[@innertext='Buscar Voo' and @visible='True']", 30000, null, "9f250258-9f4f-48a7-9d26-06bd5472465c");
                _buscarvoo_origemInfo = new RepoItemInfo(this, "BuscarVoo_Origem", ".//input[#'inputOrigin']", 30000, null, "15aed139-0246-42f9-a0e7-51077f23ce68");
                _buscarvoo_origem2Info = new RepoItemInfo(this, "BuscarVoo_Origem2", ".//input[#'inputOriginMs2']", 30000, null, "dfa5ac69-1575-4e49-995a-55e7a53ff950");
                _buscarvoo_destinoInfo = new RepoItemInfo(this, "BuscarVoo_Destino", ".//input[#'inputDestination']", 30000, null, "62d094c6-52d0-4bbb-98ce-2310bf80b3dd");
                _buscarvoo_destino2Info = new RepoItemInfo(this, "BuscarVoo_Destino2", ".//input[#'inputDestinationMs2']", 30000, null, "9247b6d7-fda6-46d1-9000-0f9b81fc1c2f");
                _checkbox_somenteidaInfo = new RepoItemInfo(this, "CheckBox_SomenteIda", ".//div[#'_smilesflightsearchportlet_WAR_smilesbookingportlet_single-leg']", 30000, null, "bbca9307-79a9-4f1c-8108-158049694b0b");
                _calendar_data1Info = new RepoItemInfo(this, "Calendar_Data1", ".//input[@id<'departure_date' or @id<'ms1_date']", 30000, null, "f06ae651-5275-41f0-965f-079afa6922d6");
                _calendar_data2Info = new RepoItemInfo(this, "Calendar_Data2", ".//input[@id<'return_date' or @id<'ms2_date']", 30000, null, "33e07ccc-575e-4704-bbae-aeb2d60c9ee3");
                _button_buscarvooInfo = new RepoItemInfo(this, "Button_BuscarVoo", ".//button[#'submitFlightSearch']", 30000, null, "8610f0de-182b-4a94-ad71-b2db886c23bf");
                _button_adicionartrechoInfo = new RepoItemInfo(this, "Button_AdicionarTrecho", ".//a[#'button-add-new-leg']", 30000, null, "362306d2-75f2-4735-ae80-8cd3e5a4ddee");
                _button_addadultoInfo = new RepoItemInfo(this, "Button_AddAdulto", ".//small[@class~'control-range add-passenger'][1]", 30000, null, "9b85b36c-33f0-4693-a6ef-d13fe0a0c09e");
                _button_addcriancaInfo = new RepoItemInfo(this, "Button_AddCrianca", ".//small[@class~'control-range add-passenger'][2]", 30000, null, "0e8c16d0-bbeb-432c-9a23-7c6aaca5e011");
                _button_addbebeInfo = new RepoItemInfo(this, "Button_AddBebe", ".//small[@class~'control-range add-passenger'][3]", 30000, null, "7e1c42d7-76a6-4f20-a386-e539c13620a0");
                _button_entrarInfo = new RepoItemInfo(this, "Button_Entrar", ".//div[#'showModalMobile']", 30000, null, "65ac6490-fb7a-4631-909f-6d5ff8a88d9a");
                _input_usuarioInfo = new RepoItemInfo(this, "Input_Usuario", ".//input[@id<'idscreenName']", 30000, null, "77ea176e-be1e-4564-b06e-31dfe7eebbf7");
                _input_senhaInfo = new RepoItemInfo(this, "Input_Senha", ".//input[@id<'password']", 30000, null, "8c1e293e-9ec8-4b5b-9f96-5dd446b11242");
                _button_submeterloginInfo = new RepoItemInfo(this, "Button_SubmeterLogin", ".//button[#'buttonSubmitLogin']", 30000, null, "645a3f24-59a0-4af6-9d2f-3100a6cc638b");
                _span_saldomilhasloginInfo = new RepoItemInfo(this, "Span_SaldoMilhasLogin", ".//span[@innertext<' milhas' and @class~'user-miles'][1]", 30000, null, "f3dd12e8-3e0f-45ff-9d68-394f456a8245");
                _home_entrarInfo = new RepoItemInfo(this, "Home_Entrar", ".//div[@innertext='Entrar']", 30000, null, "20d17b2e-cc47-4a04-a69d-6fcbaa38473e");
                _a_sairInfo = new RepoItemInfo(this, "A_Sair", ".//ul/li/a[#'logout']", 30000, null, "052918df-6277-40f2-885d-cfa4326e0818");
                _button_refazerbuscaInfo = new RepoItemInfo(this, "Button_RefazerBusca", ".//button[#'btnShowFlightSearch']", 30000, null, "318d3801-9959-4088-9234-5625a6abfaae");
                _input_taxasdinheroInfo = new RepoItemInfo(this, "Input_TaxasDinhero", ".//div[@class~'search-container-payment-method']//p//input[@id='paymentTaxesOption0'][1]", 30000, null, "990925f4-2b67-490a-9e0d-8ede9b64c975");
                _input_taxasmilhasInfo = new RepoItemInfo(this, "Input_TaxasMilhas", ".//div[@class~'search-container-payment-method']//p//input[@id='paymentTaxesOption0'][2]", 30000, null, "31dc4c9f-40a6-4fbc-8d18-b34bdf9b436a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("896b282b-52c3-44de-a91c-6d52560ab526")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("896b282b-52c3-44de-a91c-6d52560ab526")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home_MenuPrincipal item.
            /// </summary>
            [RepositoryItem("94e5852e-d1cd-4827-b49e-e22bc21b98eb")]
            public virtual Ranorex.DivTag Home_MenuPrincipal
            {
                get
                {
                    return _home_menuprincipalInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Home_MenuPrincipal item info.
            /// </summary>
            [RepositoryItemInfo("94e5852e-d1cd-4827-b49e-e22bc21b98eb")]
            public virtual RepoItemInfo Home_MenuPrincipalInfo
            {
                get
                {
                    return _home_menuprincipalInfo;
                }
            }

            /// <summary>
            /// The MenuPrincipal_BuscarVoo item.
            /// </summary>
            [RepositoryItem("9f250258-9f4f-48a7-9d26-06bd5472465c")]
            public virtual Ranorex.SpanTag MenuPrincipal_BuscarVoo
            {
                get
                {
                    return _menuprincipal_buscarvooInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MenuPrincipal_BuscarVoo item info.
            /// </summary>
            [RepositoryItemInfo("9f250258-9f4f-48a7-9d26-06bd5472465c")]
            public virtual RepoItemInfo MenuPrincipal_BuscarVooInfo
            {
                get
                {
                    return _menuprincipal_buscarvooInfo;
                }
            }

            /// <summary>
            /// The BuscarVoo_Origem item.
            /// </summary>
            [RepositoryItem("15aed139-0246-42f9-a0e7-51077f23ce68")]
            public virtual Ranorex.InputTag BuscarVoo_Origem
            {
                get
                {
                    return _buscarvoo_origemInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BuscarVoo_Origem item info.
            /// </summary>
            [RepositoryItemInfo("15aed139-0246-42f9-a0e7-51077f23ce68")]
            public virtual RepoItemInfo BuscarVoo_OrigemInfo
            {
                get
                {
                    return _buscarvoo_origemInfo;
                }
            }

            /// <summary>
            /// The BuscarVoo_Origem2 item.
            /// </summary>
            [RepositoryItem("dfa5ac69-1575-4e49-995a-55e7a53ff950")]
            public virtual Ranorex.InputTag BuscarVoo_Origem2
            {
                get
                {
                    return _buscarvoo_origem2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BuscarVoo_Origem2 item info.
            /// </summary>
            [RepositoryItemInfo("dfa5ac69-1575-4e49-995a-55e7a53ff950")]
            public virtual RepoItemInfo BuscarVoo_Origem2Info
            {
                get
                {
                    return _buscarvoo_origem2Info;
                }
            }

            /// <summary>
            /// The BuscarVoo_Destino item.
            /// </summary>
            [RepositoryItem("62d094c6-52d0-4bbb-98ce-2310bf80b3dd")]
            public virtual Ranorex.InputTag BuscarVoo_Destino
            {
                get
                {
                    return _buscarvoo_destinoInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BuscarVoo_Destino item info.
            /// </summary>
            [RepositoryItemInfo("62d094c6-52d0-4bbb-98ce-2310bf80b3dd")]
            public virtual RepoItemInfo BuscarVoo_DestinoInfo
            {
                get
                {
                    return _buscarvoo_destinoInfo;
                }
            }

            /// <summary>
            /// The BuscarVoo_Destino2 item.
            /// </summary>
            [RepositoryItem("9247b6d7-fda6-46d1-9000-0f9b81fc1c2f")]
            public virtual Ranorex.InputTag BuscarVoo_Destino2
            {
                get
                {
                    return _buscarvoo_destino2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BuscarVoo_Destino2 item info.
            /// </summary>
            [RepositoryItemInfo("9247b6d7-fda6-46d1-9000-0f9b81fc1c2f")]
            public virtual RepoItemInfo BuscarVoo_Destino2Info
            {
                get
                {
                    return _buscarvoo_destino2Info;
                }
            }

            /// <summary>
            /// The CheckBox_SomenteIda item.
            /// </summary>
            [RepositoryItem("bbca9307-79a9-4f1c-8108-158049694b0b")]
            public virtual Ranorex.DivTag CheckBox_SomenteIda
            {
                get
                {
                    return _checkbox_somenteidaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CheckBox_SomenteIda item info.
            /// </summary>
            [RepositoryItemInfo("bbca9307-79a9-4f1c-8108-158049694b0b")]
            public virtual RepoItemInfo CheckBox_SomenteIdaInfo
            {
                get
                {
                    return _checkbox_somenteidaInfo;
                }
            }

            /// <summary>
            /// The Calendar_Data1 item.
            /// </summary>
            [RepositoryItem("f06ae651-5275-41f0-965f-079afa6922d6")]
            public virtual Ranorex.InputTag Calendar_Data1
            {
                get
                {
                    return _calendar_data1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Calendar_Data1 item info.
            /// </summary>
            [RepositoryItemInfo("f06ae651-5275-41f0-965f-079afa6922d6")]
            public virtual RepoItemInfo Calendar_Data1Info
            {
                get
                {
                    return _calendar_data1Info;
                }
            }

            /// <summary>
            /// The Calendar_Data2 item.
            /// </summary>
            [RepositoryItem("33e07ccc-575e-4704-bbae-aeb2d60c9ee3")]
            public virtual Ranorex.InputTag Calendar_Data2
            {
                get
                {
                    return _calendar_data2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Calendar_Data2 item info.
            /// </summary>
            [RepositoryItemInfo("33e07ccc-575e-4704-bbae-aeb2d60c9ee3")]
            public virtual RepoItemInfo Calendar_Data2Info
            {
                get
                {
                    return _calendar_data2Info;
                }
            }

            /// <summary>
            /// The Button_BuscarVoo item.
            /// </summary>
            [RepositoryItem("8610f0de-182b-4a94-ad71-b2db886c23bf")]
            public virtual Ranorex.ButtonTag Button_BuscarVoo
            {
                get
                {
                    return _button_buscarvooInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Button_BuscarVoo item info.
            /// </summary>
            [RepositoryItemInfo("8610f0de-182b-4a94-ad71-b2db886c23bf")]
            public virtual RepoItemInfo Button_BuscarVooInfo
            {
                get
                {
                    return _button_buscarvooInfo;
                }
            }

            /// <summary>
            /// The Button_AdicionarTrecho item.
            /// </summary>
            [RepositoryItem("362306d2-75f2-4735-ae80-8cd3e5a4ddee")]
            public virtual Ranorex.ATag Button_AdicionarTrecho
            {
                get
                {
                    return _button_adicionartrechoInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Button_AdicionarTrecho item info.
            /// </summary>
            [RepositoryItemInfo("362306d2-75f2-4735-ae80-8cd3e5a4ddee")]
            public virtual RepoItemInfo Button_AdicionarTrechoInfo
            {
                get
                {
                    return _button_adicionartrechoInfo;
                }
            }

            /// <summary>
            /// The Button_AddAdulto item.
            /// </summary>
            [RepositoryItem("9b85b36c-33f0-4693-a6ef-d13fe0a0c09e")]
            public virtual Ranorex.SmallTag Button_AddAdulto
            {
                get
                {
                    return _button_addadultoInfo.CreateAdapter<Ranorex.SmallTag>(true);
                }
            }

            /// <summary>
            /// The Button_AddAdulto item info.
            /// </summary>
            [RepositoryItemInfo("9b85b36c-33f0-4693-a6ef-d13fe0a0c09e")]
            public virtual RepoItemInfo Button_AddAdultoInfo
            {
                get
                {
                    return _button_addadultoInfo;
                }
            }

            /// <summary>
            /// The Button_AddCrianca item.
            /// </summary>
            [RepositoryItem("0e8c16d0-bbeb-432c-9a23-7c6aaca5e011")]
            public virtual Ranorex.SmallTag Button_AddCrianca
            {
                get
                {
                    return _button_addcriancaInfo.CreateAdapter<Ranorex.SmallTag>(true);
                }
            }

            /// <summary>
            /// The Button_AddCrianca item info.
            /// </summary>
            [RepositoryItemInfo("0e8c16d0-bbeb-432c-9a23-7c6aaca5e011")]
            public virtual RepoItemInfo Button_AddCriancaInfo
            {
                get
                {
                    return _button_addcriancaInfo;
                }
            }

            /// <summary>
            /// The Button_AddBebe item.
            /// </summary>
            [RepositoryItem("7e1c42d7-76a6-4f20-a386-e539c13620a0")]
            public virtual Ranorex.SmallTag Button_AddBebe
            {
                get
                {
                    return _button_addbebeInfo.CreateAdapter<Ranorex.SmallTag>(true);
                }
            }

            /// <summary>
            /// The Button_AddBebe item info.
            /// </summary>
            [RepositoryItemInfo("7e1c42d7-76a6-4f20-a386-e539c13620a0")]
            public virtual RepoItemInfo Button_AddBebeInfo
            {
                get
                {
                    return _button_addbebeInfo;
                }
            }

            /// <summary>
            /// The Button_Entrar item.
            /// </summary>
            [RepositoryItem("65ac6490-fb7a-4631-909f-6d5ff8a88d9a")]
            public virtual Ranorex.DivTag Button_Entrar
            {
                get
                {
                    return _button_entrarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Button_Entrar item info.
            /// </summary>
            [RepositoryItemInfo("65ac6490-fb7a-4631-909f-6d5ff8a88d9a")]
            public virtual RepoItemInfo Button_EntrarInfo
            {
                get
                {
                    return _button_entrarInfo;
                }
            }

            /// <summary>
            /// The Input_Usuario item.
            /// </summary>
            [RepositoryItem("77ea176e-be1e-4564-b06e-31dfe7eebbf7")]
            public virtual Ranorex.InputTag Input_Usuario
            {
                get
                {
                    return _input_usuarioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Input_Usuario item info.
            /// </summary>
            [RepositoryItemInfo("77ea176e-be1e-4564-b06e-31dfe7eebbf7")]
            public virtual RepoItemInfo Input_UsuarioInfo
            {
                get
                {
                    return _input_usuarioInfo;
                }
            }

            /// <summary>
            /// The Input_Senha item.
            /// </summary>
            [RepositoryItem("8c1e293e-9ec8-4b5b-9f96-5dd446b11242")]
            public virtual Ranorex.InputTag Input_Senha
            {
                get
                {
                    return _input_senhaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Input_Senha item info.
            /// </summary>
            [RepositoryItemInfo("8c1e293e-9ec8-4b5b-9f96-5dd446b11242")]
            public virtual RepoItemInfo Input_SenhaInfo
            {
                get
                {
                    return _input_senhaInfo;
                }
            }

            /// <summary>
            /// The Button_SubmeterLogin item.
            /// </summary>
            [RepositoryItem("645a3f24-59a0-4af6-9d2f-3100a6cc638b")]
            public virtual Ranorex.ButtonTag Button_SubmeterLogin
            {
                get
                {
                    return _button_submeterloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Button_SubmeterLogin item info.
            /// </summary>
            [RepositoryItemInfo("645a3f24-59a0-4af6-9d2f-3100a6cc638b")]
            public virtual RepoItemInfo Button_SubmeterLoginInfo
            {
                get
                {
                    return _button_submeterloginInfo;
                }
            }

            /// <summary>
            /// The Span_SaldoMilhasLogin item.
            /// </summary>
            [RepositoryItem("f3dd12e8-3e0f-45ff-9d68-394f456a8245")]
            public virtual Ranorex.SpanTag Span_SaldoMilhasLogin
            {
                get
                {
                    return _span_saldomilhasloginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Span_SaldoMilhasLogin item info.
            /// </summary>
            [RepositoryItemInfo("f3dd12e8-3e0f-45ff-9d68-394f456a8245")]
            public virtual RepoItemInfo Span_SaldoMilhasLoginInfo
            {
                get
                {
                    return _span_saldomilhasloginInfo;
                }
            }

            /// <summary>
            /// The Home_Entrar item.
            /// </summary>
            [RepositoryItem("20d17b2e-cc47-4a04-a69d-6fcbaa38473e")]
            public virtual Ranorex.DivTag Home_Entrar
            {
                get
                {
                    return _home_entrarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Home_Entrar item info.
            /// </summary>
            [RepositoryItemInfo("20d17b2e-cc47-4a04-a69d-6fcbaa38473e")]
            public virtual RepoItemInfo Home_EntrarInfo
            {
                get
                {
                    return _home_entrarInfo;
                }
            }

            /// <summary>
            /// The A_Sair item.
            /// </summary>
            [RepositoryItem("052918df-6277-40f2-885d-cfa4326e0818")]
            public virtual Ranorex.ATag A_Sair
            {
                get
                {
                    return _a_sairInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The A_Sair item info.
            /// </summary>
            [RepositoryItemInfo("052918df-6277-40f2-885d-cfa4326e0818")]
            public virtual RepoItemInfo A_SairInfo
            {
                get
                {
                    return _a_sairInfo;
                }
            }

            /// <summary>
            /// The Button_RefazerBusca item.
            /// </summary>
            [RepositoryItem("318d3801-9959-4088-9234-5625a6abfaae")]
            public virtual Ranorex.ButtonTag Button_RefazerBusca
            {
                get
                {
                    return _button_refazerbuscaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Button_RefazerBusca item info.
            /// </summary>
            [RepositoryItemInfo("318d3801-9959-4088-9234-5625a6abfaae")]
            public virtual RepoItemInfo Button_RefazerBuscaInfo
            {
                get
                {
                    return _button_refazerbuscaInfo;
                }
            }

            /// <summary>
            /// The Input_TaxasDinhero item.
            /// </summary>
            [RepositoryItem("990925f4-2b67-490a-9e0d-8ede9b64c975")]
            public virtual Ranorex.InputTag Input_TaxasDinhero
            {
                get
                {
                    return _input_taxasdinheroInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Input_TaxasDinhero item info.
            /// </summary>
            [RepositoryItemInfo("990925f4-2b67-490a-9e0d-8ede9b64c975")]
            public virtual RepoItemInfo Input_TaxasDinheroInfo
            {
                get
                {
                    return _input_taxasdinheroInfo;
                }
            }

            /// <summary>
            /// The Input_TaxasMilhas item.
            /// </summary>
            [RepositoryItem("31dc4c9f-40a6-4fbc-8d18-b34bdf9b436a")]
            public virtual Ranorex.InputTag Input_TaxasMilhas
            {
                get
                {
                    return _input_taxasmilhasInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Input_TaxasMilhas item info.
            /// </summary>
            [RepositoryItemInfo("31dc4c9f-40a6-4fbc-8d18-b34bdf9b436a")]
            public virtual RepoItemInfo Input_TaxasMilhasInfo
            {
                get
                {
                    return _input_taxasmilhasInfo;
                }
            }
        }

        /// <summary>
        /// The SmilesOMelhorProgramaDeMilhasS1AppFolder folder.
        /// </summary>
        [RepositoryFolder("9bb164db-b0c4-4d27-bbb8-ffab30fc4aaf")]
        public partial class SmilesOMelhorProgramaDeMilhasS1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mensagem_botaofecharerrosInfo;
            RepoItemInfo _selecionarvoo_taxasdinheroInfo;
            RepoItemInfo _selecionarvoo_taxasmilhasInfo;

            /// <summary>
            /// Creates a new SmilesOMelhorProgramaDeMilhasS1  folder.
            /// </summary>
            public SmilesOMelhorProgramaDeMilhasS1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmilesOMelhorProgramaDeMilhasS1", "/dom[@pageurl~$URL][1]", parentFolder, 30000, null, false, "9bb164db-b0c4-4d27-bbb8-ffab30fc4aaf", "")
            {
                _mensagem_botaofecharerrosInfo = new RepoItemInfo(this, "Mensagem_BotaoFecharErros", ".//.[@class~'.*btn.*\\ close\\-content.*' and @visible='True'][1]", 30000, null, "a392d21a-28bb-440d-b207-5ba12d9dd782");
                _selecionarvoo_taxasdinheroInfo = new RepoItemInfo(this, "SelecionarVoo_TaxasDinhero", ".//div[@class~'search-container-payment-method']//input[@name~'.*paymentTaxesOption'][1]", 30000, null, "4f0aa5c5-0adf-4992-b19c-2bb77be3d418");
                _selecionarvoo_taxasmilhasInfo = new RepoItemInfo(this, "SelecionarVoo_TaxasMilhas", ".//div[@class~'search-container-payment-method']//input[@name~'.*paymentTaxesOption'][2]", 30000, null, "2936727c-cae4-4292-b914-bfd231537021");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9bb164db-b0c4-4d27-bbb8-ffab30fc4aaf")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9bb164db-b0c4-4d27-bbb8-ffab30fc4aaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Mensagem_BotaoFecharErros item.
            /// </summary>
            [RepositoryItem("a392d21a-28bb-440d-b207-5ba12d9dd782")]
            public virtual Ranorex.Unknown Mensagem_BotaoFecharErros
            {
                get
                {
                    return _mensagem_botaofecharerrosInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Mensagem_BotaoFecharErros item info.
            /// </summary>
            [RepositoryItemInfo("a392d21a-28bb-440d-b207-5ba12d9dd782")]
            public virtual RepoItemInfo Mensagem_BotaoFecharErrosInfo
            {
                get
                {
                    return _mensagem_botaofecharerrosInfo;
                }
            }

            /// <summary>
            /// The SelecionarVoo_TaxasDinhero item.
            /// </summary>
            [RepositoryItem("4f0aa5c5-0adf-4992-b19c-2bb77be3d418")]
            public virtual Ranorex.InputTag SelecionarVoo_TaxasDinhero
            {
                get
                {
                    return _selecionarvoo_taxasdinheroInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SelecionarVoo_TaxasDinhero item info.
            /// </summary>
            [RepositoryItemInfo("4f0aa5c5-0adf-4992-b19c-2bb77be3d418")]
            public virtual RepoItemInfo SelecionarVoo_TaxasDinheroInfo
            {
                get
                {
                    return _selecionarvoo_taxasdinheroInfo;
                }
            }

            /// <summary>
            /// The SelecionarVoo_TaxasMilhas item.
            /// </summary>
            [RepositoryItem("2936727c-cae4-4292-b914-bfd231537021")]
            public virtual Ranorex.InputTag SelecionarVoo_TaxasMilhas
            {
                get
                {
                    return _selecionarvoo_taxasmilhasInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SelecionarVoo_TaxasMilhas item info.
            /// </summary>
            [RepositoryItemInfo("2936727c-cae4-4292-b914-bfd231537021")]
            public virtual RepoItemInfo SelecionarVoo_TaxasMilhasInfo
            {
                get
                {
                    return _selecionarvoo_taxasmilhasInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}