///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POCSmiles.Selecao_De_Voos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VC_Pedido recording.
    /// </summary>
    [TestModule("523080ae-03e9-46cf-89b8-217b2cb4ee66", ModuleType.Recording, 1)]
    public partial class VC_Pedido : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POCSmiles.SmilesRepository repository.
        /// </summary>
        public static POCSmiles.SmilesRepository repo = POCSmiles.SmilesRepository.Instance;

        static VC_Pedido instance = new VC_Pedido();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VC_Pedido()
        {
            voo1 = "";
            voo2 = "";
            tarifaPorAdultoMilhas = "";
            tarifaPorAdultoDinheiro = "";
            taxasDinheiro = "";
            taxasMilhas = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VC_Pedido Instance
        {
            get { return instance; }
        }

#region Variables

        string _voo1;

        /// <summary>
        /// Gets or sets the value of variable voo1.
        /// </summary>
        [TestVariable("6bbee9e5-9a77-47ab-971f-06d93af737de")]
        public string voo1
        {
            get { return _voo1; }
            set { _voo1 = value; }
        }

        string _voo2;

        /// <summary>
        /// Gets or sets the value of variable voo2.
        /// </summary>
        [TestVariable("6967fa8e-5dc3-4874-b7ba-06c66c3f2cce")]
        public string voo2
        {
            get { return _voo2; }
            set { _voo2 = value; }
        }

        string _tarifaPorAdultoMilhas;

        /// <summary>
        /// Gets or sets the value of variable tarifaPorAdultoMilhas.
        /// </summary>
        [TestVariable("3a41a517-35d8-430b-9156-5cf7f9754fc2")]
        public string tarifaPorAdultoMilhas
        {
            get { return _tarifaPorAdultoMilhas; }
            set { _tarifaPorAdultoMilhas = value; }
        }

        string _tarifaPorAdultoDinheiro;

        /// <summary>
        /// Gets or sets the value of variable tarifaPorAdultoDinheiro.
        /// </summary>
        [TestVariable("52959b9f-93d9-4fd4-b189-16f9e27adbd2")]
        public string tarifaPorAdultoDinheiro
        {
            get { return _tarifaPorAdultoDinheiro; }
            set { _tarifaPorAdultoDinheiro = value; }
        }

        string _taxasDinheiro;

        /// <summary>
        /// Gets or sets the value of variable taxasDinheiro.
        /// </summary>
        [TestVariable("225b88a1-df49-4ac8-91f4-976a1a26d09b")]
        public string taxasDinheiro
        {
            get { return _taxasDinheiro; }
            set { _taxasDinheiro = value; }
        }

        string _taxasMilhas;

        /// <summary>
        /// Gets or sets the value of variable taxasMilhas.
        /// </summary>
        [TestVariable("624f9b94-b3a2-4971-8b6d-2e2467f32098")]
        public string taxasMilhas
        {
            get { return _taxasMilhas; }
            set { _taxasMilhas = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CaptureValues();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SmilesOMelhorProgramaDeMilhasS1.PValidacao_DetalhesPedido, false, new RecordItemIndex(1));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
